### ISSUE TITLE
dub complains about syntax errors?

### ISSUE THREAD

**Issue by RandomInsano** [rejectedsoftware/vibe.d#1003]
I must be doing something wrong here. I've installed everything according to the readme on a Ubuntu 14.04 OpenVZ container.

I'm somehow getting a bunch of syntax errors with `dub`.
http://pastebin.com/YXfH3BHK

I'm absolutely new to all of this. Hopefully this is user error.

**Comment by s-ludwig** [comment]
Looks like possibly the compiler is too old. Which version do you have installed?

**Comment by RandomInsano** [comment]
Whoops. You're totally right. I grabbed the ones from the doc page, so I guess modify this into a bug report for the docs?

```
sudo apt-get install g++ gcc-multilib xdg-utils
wget "http://ftp.digitalmars.com/dmd_2.062-0_amd64.deb"
sudo dpkg -i dmd_2.062-0_amd64.deb
```

**Comment by s-ludwig** [comment]
Oh yeah, those lines haven't been touched in ages. They should probably just mention the official DMD download page instead. For now, I've updated the links to the latest version.
