### ISSUE TITLE
Disable --uid and --gid

### ISSUE THREAD

**Issue by rikkimax** [rejectedsoftware/vibe.d#1030]
On Windows they are not relevant as the lowering isn't implemented.
It should also be able to be disabled in case of alternatives such as within daemonize.

https://github.com/rejectedsoftware/vibe.d/blob/b9c5a68dd7e09d85c2e6d3f9d34ca7b9045f1798/source/vibe/core/core.d#L1339

**Comment by s-ludwig** [comment]
Are you thinking about adding a command line option or something to be called during initialization time? The former would be a good idea. The latter can already be easily achieved by writing a custom `main()`, so it probably isn't worth to add an explicit API for that, considering that it would be quite a rarely used feature.

**Comment by rikkimax** [comment]
Neither. Just wrap the two calls to getOption with a version statement.

```D
version(VibeWithoutGetUidGid) {}
else {
    //...
}
```

It shouldn't change the default case and it allows to not have them present if vibe.core.args is used in user applications.
I was thinking along the same lines for logging. As an alternative logging mechanism might be used. Verbose options wouldn't be much use. Only clutter it all up. But unlike uid/gid, is a bigger issue as it conflicts with real values.

**Comment by s-ludwig** [comment]
Why not simply completely go without vibe.d's default command line options?

```
void main()
{
    runEventLoop();
}
```

**Comment by rikkimax** [comment]
It is not possible to use vibe.core.args without these arguments being added automatically.
In other words, there is no way to disable vibe.d's default command line options and use that module currently.

**Comment by s-ludwig** [comment]
Hm okay, that's a point. Would you personally be okay with having a single `VibeNoDefaultArgs` to disable all default arguments at once? It would be easy to recreate the missing switches if needed and I'd rather not create an explosion of versions just to provide fine-grained configurability for a feature that is so rarely used (supposedly).

**Comment by rikkimax** [comment]
Yeah I'm fine with it.
Another thing that really needs added is the ability to provide the args to it. Instead of getting it itself.

Basically I think vibe.core.args needs a bit of love to make it more usable outside of vibe's use case. But this is the most intrusive change.

**Comment by s-ludwig** [comment]
> Another thing that really needs added is the ability to provide the args to it. Instead of getting it itself.

Yeah, that's unfortunately a little bit difficult, because the configuration flags are needed at module construction time. You can't really intercept that from high level code unless you override the C `main()`. It would of course be possible to process command line options *again* at a later point, though. Combined with `VibeNoDefaultArgs` this could be implemented as a purely additive change.
