### ISSUE TITLE
Diet/Jade tag attribute=')'

### ISSUE THREAD

**Issue by vuaru** [rejectedsoftware/vibe.d#1033]
```input(placeholder=')')``` fails to to compile, but is valid jade.

Probably happens on other symbols as well.

**Comment by vuaru** [comment]
I just checked, seems it also happens on ```'('```.

**Comment by s-ludwig** [comment]
With the fixed code, too?

**Comment by vuaru** [comment]
Just checked with master, works.
Sorry.

**Comment by s-ludwig** [comment]
Thanks for verifying!
