### ISSUE TITLE
Deprecating SSLContext and SSLStream

### ISSUE THREAD

**Issue by etcimon** [rejectedsoftware/vibe.d#1049]
I'd like to rename it to TLSContext and TLSStream, considering the standards are also deprecated and OpenSSL is the only "thing" to actually carry the SSL name anymore.

**Comment by s-ludwig** [comment]
Yeah agreed, this is actually something that has bugged me for a long time!

**Comment by s-ludwig** [comment]
Had to force-overwrite history to get a proper diff.

**Comment by etcimon** [comment]
> Yeah agreed, this is actually something that has bugged me for a long time!

It shows, I've never seen you adopt a change so quickly =)

**Comment by s-ludwig** [comment]
Sometimes it's good to get a kick in the pants to get something done ;)  (if that's the right way to put this in English)

**Comment by etcimon** [comment]
> Sometimes it's good to get a kick in the pants to get something done ;) (if that's the right way to put this in English)

Haha that sounds like you'd be on your knees, no it's the other way around: kick in the arse (to be polite)
