### ISSUE TITLE
WebSocket client

### ISSUE THREAD

**Issue by WebFreak001** [rejectedsoftware/vibe.d#1051]
It would be nice if there would be an WebSocket client for connecting to externals servers and redirecting that output to the user and process it on the server.

**Comment by dariusc93** [comment]
@WebFreak001 you mean like for the client-side (eg javascript) or a vibe.d websocket client that connects to another server that has websockets?

**Comment by WebFreak001** [comment]
No I want the vibe.d server to connect to a websocket server. There is also TCPclient so why not WebSocket client

**Comment by dariusc93** [comment]
@WebFreak001 well websocket was not made for server-to-server connection. It shouldnt be to hard to implement but to me honestly do not see the point. maybe @s-ludwig could talk explain?

**Comment by WebFreak001** [comment]
I want to make a chat bot for hitbox (which uses websockets). I used nodejs before but now i switched to vibe.d because not having actual classes in javascript (Not prototype stuff, JSON or new Function) is really annoying. (I tried TypeScript but the compiler is bugged and now I really hate it and I dont like coffeescript or dart)

**Comment by s-ludwig** [comment]
This would be relatively straight forward to do, mostly reusing the existing code. I can't personally promise a date when I would have the time to actually implement and test it, though.

**Comment by dariusc93** [comment]
@WebFreak001 is the websockets are for javascript for client-side to talk to the server and youre trying to talk to another server at the same time, you could look into using the rest interface. I use the rest interface to send data back and forth between the servers (I would use tcp for that but i decided to just use rest for now). Like @s-ludwig said, it should be straight forward. I dont think it should be to hard to do though, but I moved to vibe.d because I did get tired of node.js. I normally try to stick with system languages like go, d, rust, c/c++.

**Comment by etcimon** [comment]
The client basically does the inverse of the server negotiation: https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/http/websockets.d#L69

I would suggest to follow the RFC.

As for the Websocket class and all the rest, I don't think there's any difference. Probably a 100 lines of code missing there.

**Comment by s-ludwig** [comment]
If not even much less!

**Comment by etcimon** [comment]
The only particularities I can see is this

> Clients MUST choose a new masking key for each frame
> (the data from the server to the client is not masked).

> WebSocket clients verify that the server included one of the values that was specified in the WebSocket client's handshake.

**Comment by etcimon** [comment]
Usage would look like this:

```D
void handler(WebSocket ws) { .. }

requestHTTP( (scope req) { handleWebsocket(&handler, req); }, (scope res) { bodyReader.dump(); });
```

The HTTPClientRequest will need a `switchProtocol`

**Comment by yannick** [comment]
this could also be useful to build a rpc system over websocket e.g. with msgpack-d

**Comment by WebFreak001** [comment]
Just found out about `connectWebSocket`, seems to be implemented already
