### ISSUE TITLE
libevent2.d:97: undefined reference to `event_set_mem_functions' on gentoo linux

### ISSUE THREAD

**Issue by gronka** [rejectedsoftware/vibe.d#1055]
This is what I get when I run:
dub init smashfuse vibe.d
cd smashfuse
dub build

Compiling using dmd...
Linking...
../../../.dub/packages/vibe-d-0.7.23/libvibe-d.a(libevent2_32da_5d7.o): In function `_D4vibe4core7drivers9libevent215Libevent2Driver6__ctorMFNbC4vibe4core6driver10DriverCoreZC4vibe4core7drivers9libevent215Libevent2Driver':
/home/taylor/projects/smashfuse/smashfuse/../../../.dub/packages/vibe-d-0.7.23/source/vibe/core/drivers/libevent2.d:97: undefined reference to `event_set_mem_functions'
collect2: error: ld returned 1 exit status
--- errorlevel 1
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2066-418F4DD6CDD1AE0EFCC533D25B9B948A/ smashfuse executable
Error executing command build: dmd failed with exit code 1.

I have dev-libs/libevent-2.1.5 installed, both 64-bit and 32-bit. I also downgraded to libevent-2.0.22, although the problem persists. After downgrading I ran ldconfig and deleted the ~/.dub directory.
I am using dmd-2_066, with that useflag set on dev-utils/dub, and eselect set.

Here is the output of dub build -v
https://gist.github.com/gronka/5b9a6d8b0ca09dcc70ff

**Comment by gronka** [comment]
I'm wondering if the EVENT_SET_MEM_FUNCTIONS flag is disabled by default - it doesn't appear to be disabled in the ebuild https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-libs/libevent/libevent-2.1.5.ebuild?view=markup

**Comment by gronka** [comment]
vibe.d runs with libevent linked from the readme. Thanks for that.

**Comment by Zoadian** [comment]
looks like you have to build libevent with the debug useflag enabled

**Comment by whitebyte** [comment]
Just ran into it using Calculate Linux, a Gentoo-based distro. Enabling debug useflas with `# USE="debug" emerge libevent` works like a charm.

@s-ludwig please consider adding a small note on this issue to the Vibe.d build instructions.
