### ISSUE TITLE
Removal or rewrite passwordhash

### ISSUE THREAD

**Issue by dariusc93** [rejectedsoftware/vibe.d#1056]
I feel that the passwordhash should be removed since its deprecated or rewrite it to have it support sha2 for 2.066 and 2.067

**Comment by dariusc93** [comment]
Closing since there is a better alt (it might be worth removing the function if its not already removed)

**Comment by s-ludwig** [comment]
Is there something secure and ready to use, using bcrypt or a HMAC mechanism? code.dlang.org still uses the old MD5 passwords and should really be upgraded. I always wanted to implement something that is backwards compatible with the passwords stored in /etc/passwd (or shadow) (in particular, it should store the hash function used along with the password, so that seamless upgrades are possible), but never had the time to finish it.

**Comment by dariusc93** [comment]
For normal passwords, I would probably suggest bcrypt. It is secured and easy to setup and use. I do know botan has support for bcrypt and a wrapper can be made for it. HMAC could be used but that requires a key to use against the hash. Maybe @etcimon can give his opinion on the matter? 

Also, why store the passwords in /etc/passwd or are you implying something similar to passwd?

**Comment by etcimon** [comment]
Yes, bcrypt is recommended to avoid a password leak disaster

**Comment by s-ludwig** [comment]
Thanks, my question was targeted more at the existence of a D package that does this in a ready to use way (one function call to generate a hash and one to test). How is the state of Botan on Windows, or w.r.t. to compile time resources these days? I guess Stefan's work on the CTFE engine should be a huge win there.

> Also, why store the passwords in /etc/passwd or are you implying something similar to passwd?

Something similar - I particular I'd just like to use the same encoding for storing the hashes. It prefixes an identifier for the hash algorithm used and supports a number of hash schemes. The nice thing would be that several unix tools could then be used to work with those. See https://en.wikipedia.org/wiki/Crypt_(C) for a format description.

**Comment by etcimon** [comment]
The Botan package compiles fine in debug mode, within 10-30s on my machine. In release mode, it can take up to 15 minutes on win x86 for some reason. On linux/release it compiles within 1-2 min in release mode. Linkage is fast on all platforms.
