### ISSUE TITLE
REST breaks queries?

### ISSUE THREAD

**Issue by IgorStepanov** [rejectedsoftware/vibe.d#1140]
I wrote a simple rest interface to the OrientDB server.

```
interface IOrientDBRoot
{
    @property IOrientDBQuery query();
}



interface IOrientDBQuery
{
    @method(HTTPMethod.GET)
    @path(":db_name/sql/:query/:result_set_size")
    Json sql(string _db_name, string _query, int _result_set_size);
}
```
I called sql method with `_query="select DownloadedDateTime from Message"` and I got an error.
In logs I see the following line:
`GET /query/twitter_data/sql/select%2520DownloadedDateTime%2520from%2520Message/1 HTTP/1.1`
However, correct query should looks `/query/twitter_data/sql/select%20DownloadedDateTime%20from%20Message/1`

This bug looks like rest inteface handler calls filterURLEncode twice: `filterURLEncode(filterURLEncode("select DownloadedDateTime from Message"))`
Is it really bug, I do something wrong?

**Comment by IgorStepanov** [comment]
Yes, the path is encoded in the `vibe.web.rest` module [first time](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/web/rest.d#L1011)
and after that, it done in [URL.localURI](https://github.com/rejectedsoftware/vibe.d/blob/4070d0645b94c68471109a76b18ba18ececb6399/source/vibe/inet/url.d#L164).
What we may do with it?

**Comment by Geod24** [comment]
I can reproduce. We can probably ditch this URLEncode. I'll write a complete test case.

**Comment by Geod24** [comment]
#1141

**Comment by IgorStepanov** [comment]
@Geod24 Thanks! I've written one possible regression test in PR disscussion

**Comment by Geod24** [comment]
Since #1143 gets merged, this can be closed

**Comment by IgorStepanov** [comment]
Yep.
