### ISSUE TITLE
REST client doesn't support (typesafe) variadic arguments

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/vibe.d#1144]
The current implementation uses `ParameterTuple` to define the parameters of the overridden function. However, `ParameterTuple` doesn't contain the ellipses part of the last parameter (e.g. `void foo(string[] bar...)`) and thus the generated method doesn't override the corresponding one in the interface. This used to work in earlier versions where the parameter declaration was done using a string mixin.

**Comment by Geod24** [comment]
Out of interest, what's the use case for this ? Is it relatd to http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/25596/ ?

**Comment by Geod24** [comment]
Can be closed.

**Comment by Geod24** [comment]
Ping @s-ludwig
