### ISSUE TITLE
/usr/bin/ld: Cannot find levent

### ISSUE THREAD

**Issue by gencube** [rejectedsoftware/vibe.d#1154]
Hi,

I am new to Dlang, and is trying out your code:

/usr/bin/ld: cannot find -levent

this is what I run:
```bash
vibe.d-master/examples/http_server $ dub
Fetching libasync 0.7.3 (getting selected version)...
Placing libasync 0.7.3 to /home/mattong/.dub/packages/...
Building vibe-d ~master configuration "libevent", build type debug.
Running dmd...
Building http-server-example ~master configuration "application", build type debug.
Compiling using dmd...
Linking...
/usr/bin/ld: cannot find -levent
/usr/bin/ld: cannot find -levent_pthreads
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
--- errorlevel 1
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2067-FE1C6F7F0A77C0BE051055AAAEEEEAF0/ http-server-example executable
Error executing command run:
dmd failed with exit code 1.
```

**Comment by Geod24** [comment]
Hello,
As mentionned in the README, you need to install extra dependencies: https://github.com/rejectedsoftware/vibe.d/blob/master/README.md#additional-setup-on-linux-debianubuntumint

**Comment by Geod24** [comment]
@gencube : Any chance you can close this ?

In addition, if you have any question, you can either ask on the forum (http://forum.dlang.org/group/learn for any D-related question, http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/ if it's vibe.d specific), or come to IRC (we have an underpopulated `#vibe.d` channel, but there are folks knowledgeable on `#d` too).

**Comment by gencube** [comment]
Cool. It is now working. BTW, any good sample source for a file server like this one?
Undertow (JBoss in Java).
https://github.com/undertow-io/undertow/blob/master/examples/src/main/java/io/undertow/examples/fileserving/FileServer.java
