### ISSUE TITLE
0.7.24-beta.3 Can't register WebInterface with index page (/ path)

### ISSUE THREAD

**Issue by olehlong** [rejectedsoftware/vibe.d#1173]
After recent update i can't register a WebInterface with index page that has "/" path.
Used to work (beta 1):
```
void index() {
	render!("index.dt");
}
```
or (from an example)
```
@path("/")
void getHome() {
	render!("index.dt");
}
```
Now they throw an exception:
vibe-d-0.7.24-beta.3/source/vibe/http/router.d(130): Cannot register null or empty path!

**Comment by s-ludwig** [comment]
Has been fixed by 118835fe0ae3ed8e7b69756241aa24105eb85e3c - I'll tag a new beta as soon as #1153 got merged.

**Comment by vuaru** [comment]
@s-ludwig Just ran into this, and #1153 is now merged. :smile:

**Comment by s-ludwig** [comment]
Ah, I was already looking for the issue where I wrote that I'd create a new tag... but didn't find it ^^

Done now (code.dlang.org is also updated).
