### ISSUE TITLE
want synchronous HTTP get/download

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#1207]
It's quite a pain that there is no synchronous API alternative to http://vibed.org/api/vibe.http.client/requestHTTP using Fiber's to perform the request asynchronously.

**Comment by yazd** [comment]
The API is already synchronous (while being performed asynchronously). The delegates are only there to limit the scope of `HTTPClientResponse` and ensure its proper destruction. The call won't return before the response is handled.

**Comment by MartinNowak** [comment]
Oh, thanks. So this is something, that could be solved by http://wiki.dlang.org/DIP69#Classes.

**Comment by MartinNowak** [comment]
It's still a joke to write such code.
```d
void download(Track[] tracks)
{
    foreach (t; tracks)
    {
        bool done;
        string url = t.url~"?client_id="~client_id;
        while (!done) {
            requestHTTP(url,
                (scope req) {
                },
                (scope res) {
                    if (res.statusCode / 100 == 3)
                    {
                        url = res.headers["Location"];
                    }
                    else
                    {
                        auto f = openFile("tmp/"~t.filename, FileMode.createTrunc);
                        f.write(res.bodyReader);
                        f.close();
                        done = true;
                    }
                }
            );
        }
    }
}
```

At least the `-L` follow location functionality of curl should be an option.
Furthermore it could be possible to return the HTTPClientResponse wrapped with unique ownership in a non-copyable struct, so that all resources are freed when that is destroyed. Not sure if the lifetime of all resources can be easily attached to the response.

**Comment by s-ludwig** [comment]
Not sure if the last comment got deleted, or if I'm having issues with the abysmal internet connection here, but just in case, you should have a look at `vibe.inet.urltransfer` (The module `vibe.inet` is unfortunate, because it is supposed to contain low-level functionality, and is subject to change). It implements automatic redirection handling, as well as saving to a file.
