### ISSUE TITLE
Make Json struct work with std.experimental.logger

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [rejectedsoftware/vibe.d#1234]
The experimental logger seems to require a `@safe toString()` function to print the content of an object which the `Json struct` in vibe doesn't seem to provide.

The `Nullable` type had the same problem and was fixed this way: https://github.com/D-Programming-Language/phobos/pull/3582

**Comment by s-ludwig** [comment]
In the end I had to resort to `@trusted`, because @safe inference failed for some reason and the only other solution was to copy/paste the whole body of `writeJsonString`. But the upside is that there is now also a `toString()` that doesn't allocate.
