### ISSUE TITLE
Memory leak warning: struct dtor doesn't get called anymore

### ISSUE THREAD

**Issue by etcimon** [rejectedsoftware/vibe.d#1240]
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/utils/memory.d#L510

This no longer works with DMD 2.068, due to different .destroy strategy in druntime

I was prompted to debug this with this error:
https://travis-ci.org/etcimon/memutils/builds/78150113

And has to create a compatibility layer here:
https://travis-ci.org/etcimon/memutils/builds/78225850

The only fix I've found was to re-implement the old `.destroy` (in this case I reimplemented it as `_destroy` in `memutils._destroy`)

**Comment by dariusc93** [comment]
So I would have to use 2.067 if i want to avoid this being an issue until this is reimplemented (or rewritten)?

**Comment by etcimon** [comment]
Yes, since this is final behavior for druntime 2.068+ I don't see any way to move forward without patching vibe.d. It will require a fix in memory.d that uses this new _destroy function: https://github.com/etcimon/memutils/blob/master/source/memutils/_destroy.d

On my end, memutils was patched on master which covers the rest of the libraries (libhttp2, libasync, botan, etc) so it's not a problem.

**Comment by s-ludwig** [comment]
Looking at the implementation, I can't see yet why it wouldn't work now. It also doesn't appear so from a quick test: http://dpaste.dzfl.pl/c574ad0bf11a

**Comment by etcimon** [comment]
I think the problem is double destruction maybe? Did I make a mistake on this dpaste?
http://dpaste.dzfl.pl/187a94955eb1

**Comment by etcimon** [comment]
The unit tests from memutils were failing on the 2.068 druntime release, and it works with the legacy destroy logic, so I'm very certain that the new behavior is wrong

**Comment by s-ludwig** [comment]
The double-free is fine - once using `destroy` and once using the GC at Druntime shutdown. But the second one happens on an uninitialized instance (`T.init`), so the destructor should be a no-op. In fact it's sometimes the case that a destructor is called on an internal `T.init` value when passing around structs, so the destructor should always have a corresponding check: http://dpaste.dzfl.pl/9cab9d7de950

**Comment by MartinNowak** [comment]
> on an uninitialized instance (T.init)

Better call that default initialized, uninitialized means random data.

**Comment by s-ludwig** [comment]
Sorry, right, "uninitiailzed" was indeed the wrong term!

**Comment by etcimon** [comment]
Ok I took a second to revert the compatibility layer and add some dmd versions for the struct dtor test:
https://travis-ci.org/etcimon/memutils

Conclusively it's still a problem in DMD 2.068.2-b1

**Comment by MartinNowak** [comment]
The problem is that [`__xdtor`](https://github.com/D-Programming-Language/druntime/blob/c68373a215050fea77820c73a2d2a18f3b93c36b/src/object.d#L2309) is skipped for `Vector!(ubyte, ALLOC)`.
It's probably a regression introduced by https://github.com/D-Programming-Language/druntime/pull/1312.

**Comment by s-ludwig** [comment]
One thing I noticed while reading through the source: https://github.com/etcimon/memutils/blob/d58d8c716376513ef53db12beaffc83a3c56f73e/source/memutils/vector.d#L245
This is not a good idea, because it doesn't generally do the right thing. Casting a byte[] array to an int[] array will produce wrong numbers, or casting an array of objects to an array of base interfaces will result in corrupt pointers.

**Comment by etcimon** [comment]
> This is not a good idea, because it doesn't generally do the right thing. Casting a byte[] array to an int[] array will produce wrong numbers

I think this ended up being a simplification of this: https://github.com/D-Programming-Language/phobos/blob/master/std/container/array.d#L368

I think it worked out in the context I wanted it to be in, I'd have to look into it more

**Comment by MartinNowak** [comment]
See [Issue 15044 – [Reg 2.068.0] destroy might leak memory](https://issues.dlang.org/show_bug.cgi?id=15044) for a reduced test case.

**Comment by etcimon** [comment]
Wow thanks, I wasn't sure how to isolate this. Did you run dustmite on it?

**Comment by s-ludwig** [comment]
> I think this ended up being a simplification of this: https://github.com/D-Programming-Language/phobos/blob/master/std/container/array.d#L368

The difference is that the original code uses `emplace` to convert each element individually instead of casting the array slice as a whole. I'd just remove the cast and let `Data.this` handle the conversion per element when necessary.

**Comment by s-ludwig** [comment]
@etcimon, can you confirm that DMD 2.068.2 has fixed this for you?
