### ISSUE TITLE
Cannot connect to MongoDB 3.0 using authentication.

### ISSUE THREAD

**Issue by hpohl** [rejectedsoftware/vibe.d#1243]
Connecting to MongoDB 3.0 using authentication `mongodb://user:password@host` fails but works with 2.6. I did some research and they changed the mechanism in 3.0: http://docs.mongodb.org/manual/core/authentication/#authentication-mechanisms.

**Comment by dariusc93** [comment]
I do know that 3.x has a api change so i dont know if this impacts vibe.

**Comment by s-ludwig** [comment]
I've added a speculative fix on master. Can you check if that fixes the issue?

**Comment by hpohl** [comment]
Nope, still doesn't work here.

**Comment by s-ludwig** [comment]
If you look at the server log, does it say "MONGODB-CR credentials missing"? In that case, you should be able to work around it like this: http://stackoverflow.com/questions/29006887/mongodb-cr-authentication-failed

The only other solution is to implement the SHA-1 authentication method, or to go with the certificate based one (#1235, not yet sure about exposing `MongoClientSettings`).

**Comment by s-ludwig** [comment]
> If you look at the server log, does it say "MONGODB-CR credentials missing"?

\* It does for me, after setting up a quick test database.

**Comment by hpohl** [comment]
Nice, that worked for me as well. If none of these solutions make it into 0.7.25 there should be a documentation note so people don't waste time trying to debug it.

**Comment by s-ludwig** [comment]
Good point. I'll add a note to the documentation of `connectMongoDB`.

**Comment by dariusc93** [comment]
Will there ever be complete support for 3.x?

**Comment by s-ludwig** [comment]
Someone will have to do the work for implementing the SHA-1 auth method. I'm currently not able to do it myself.

**Comment by MartinNowak** [comment]
There seems to be a couple of other MongoDB 3.x API changes, rendering several command inoperable.
