### ISSUE TITLE
master doesn't compile using LDC alpha

### ISSUE THREAD

**Issue by Laeeth** [rejectedsoftware/vibe.d#1249]
/usr/include/dlang/ldc/core/atomic.d(327): Error: static assert  "Cannot atomically load/store type of size 16LU"
/usr/include/dlang/ldc/core/atomic.d(337):        instantiated from here: _AtomicType!(shared(HTTPServerContext)[])
../../../../../home/laeeth/.dub/packages/vibe-d-master/source/vibe/http/server.d(1334):        instantiated from here: atomicLoad!(cast(MemoryOrder)3, shared(HTTPServerContext)[])

arch linux 64

**Comment by s-ludwig** [comment]
Fixed by #1255.
