### ISSUE TITLE
Event driver not properly initialized

### ISSUE THREAD

**Issue by chalucha** [rejectedsoftware/vibe.d#1250]
I'm trying to build the REST API with HTTPServerOption.distribute on but it often fails with:

Worker thread terminated due to uncaught error: No event driver loaded. Did the vibe.core.core module constructor run?

after startup.

I'm on windows 8.1 x86_64, vibe latest alpha, compiled with libevent configuration, dmd 2.068.1

**Comment by etcimon** [comment]
I recommend DMD 2.067.1,  due to a struct dtor issue in 2.068+

I also don't think the distribute option should exist. You should either run worker tasks and send/receive in vibe.core.concurrency at higher level for compute-intensive jobs, or create multiple processes listening to different ports serving a load balancer.

**Comment by chalucha** [comment]
I noticed the same behavior when calling runWorkerTaskH
It seems to be new with 2.068.1 because it works ok with 2.068.0

**Comment by chalucha** [comment]
Ok, I've made a sample to reproduce it.
Just used upload sample from examples with a added worker thread after fileupload.

http://pastebin.com/9mj6MSkU

When used without custom main (same as in vibe.d sources) it works. When used with custom main, it fails.
At least with dmd 2.068.1 and 2.068.2-b1 on windows x86_64 with default libevent driver.
It is ok on linux and same windows with 2.068.0

**Comment by MartinNowak** [comment]
> I recommend DMD 2.067.1, due to a struct dtor issue in 2.068+ which wasn't patched yet in vibe.d

Do you have more details about this @etcimon?

**Comment by s-ludwig** [comment]
@MartinNowak, see also #1240.

**Comment by chalucha** [comment]
I've tried this again at home on linux and there is an error with dmd-2.068.1, but not with dmd-2.068.2-b1 or dmd-2.068.0 so I think, this can be closed

**Comment by yebblies** [comment]
I saw the same problem with 2.068.1 in one of my projects, and can confirm it's gone in 2.068.2-b1.
