### ISSUE TITLE
Running dub build results in linking error: main not found

### ISSUE THREAD

**Issue by frigginglorious** [rejectedsoftware/vibe.d#1283]
Hi!

This is what my dub.json deps look like:

"dependencies": {
                "vibe-d": "~master"
        }

When doing dub I get this:

WARNING: A deprecated branch based version specification is used for the dependency vibe-d. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Selected package libev 4.0.0+4.04 does not match the dependency specification >=5.0.0+4.04 <5.1.0 in package vibe-d. Need to "dub upgrade"?
Selected package libasync 0.6.6 does not match the dependency specification 0.7.5 in package vibe-d. Need to "dub upgrade"?
Performing "debug" build using dmd for x86_64.
vibe-d ~master: target for configuration "libevent" is up to date.
testy ~master: building configuration "application"...
Linking...
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
...
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.

This is with:

$ dub --version
DUB version 0.9.24, built on Aug 19 2015

$ dmd --version
DMD64 D Compiler v2.068.2
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright

Running just dmd on a test file works fine (as in hello world). The above happens while using the vibe.d examples, or with my program which worked months ago.

**Comment by s-ludwig** [comment]
It looks like no  `main()` function is defined. That either needs to happen in the application package, or you need `"versions": ["VibeDefaultMain"]` to use the pre-defined implementation of vibe.d.

**Comment by frigginglorious** [comment]
Thanks so much man!
