### ISSUE TITLE
Probably a bug in REST API gen

### ISSUE THREAD

**Issue by chalucha** [rejectedsoftware/vibe.d#1285]
I have a REST method with params: `out long totalCount, int skip = 0, int take = 100`

I tried it with 0.7.26-alpha, but it failed to build on this assert:
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/web/rest.d#L716 (btw it could be more informative).

As it turned out it was a problem with the `skip` parameter marked as out.

I think that the problem is here:
https://github.com/rejectedsoftware/vibe.d/blob/v0.7.26-alpha.2/source/vibe/web/internal/rest/common.d#L233

there is used ParameterStorageClasses from all params to set in/out of single one.

I replaced
`foreach (SC; ParameterStorageClassTuple!func) {`
with
`enum SC = ParameterStorageClassTuple!func[i];`

and it seems to work, but I did not look at it properly

**Comment by s-ludwig** [comment]
Accidentally committed to the "rest-refactor" branch, but that should hopefully be merged to master in one or two days. But I've fixed it exactly like you did above.
