### ISSUE TITLE
Multiple loggers - not logging what they should

### ISSUE THREAD

**Issue by chalucha** [rejectedsoftware/vibe.d#1294]
Is this break intended?
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/core/log.d#L127

It causes that when you are using multiple loggers (for example one for console output and one for file output and one for syslog) it does not log the line to other loggers even though they has valid min log level to also log it.

**Comment by s-ludwig** [comment]
It was a relict that I missed in the old code that didn't yet use a range interface for writing log messages.
