### ISSUE TITLE
 0.7.26-beta.1 linking error os x

### ISSUE THREAD

**Issue by yannick** [rejectedsoftware/vibe.d#1300]
0.7.26-beta.1 (and master) gives me a linking error on os x:
 tested: dmd-2.068.2 and v2.069

```
dub init -t vibe.d blahz
```
then edit dub.json and add 0.7.26-beta.1 vibe.d dependency.
result:

```
Performing "debug" build using dmd for x86_64.
Building vibe-d 0.7.26-beta.1 configuration "libevent"...
Building blahz ~master configuration "application"...
Linking...
Undefined symbols for architecture x86_64:
  "_TLSv1_1_client_method", referenced from:
      _D4vibe6stream7openssl14OpenSSLContext6__ctorMFE4vibe6stream3tls14TLSContextKindE4vibe6stream3tls10TLSVersionZC4vibe6stream7openssl14OpenSSLContext in libvibe-d.a(openssl_4273_569.o)
  "_TLSv1_1_server_method", referenced from:
      _D4vibe6stream7openssl14OpenSSLContext6__ctorMFE4vibe6stream3tls14TLSContextKindE4vibe6stream3tls10TLSVersionZC4vibe6stream7openssl14OpenSSLContext in libvibe-d.a(openssl_4273_569.o)
  "_TLSv1_2_client_method", referenced from:
      _D4vibe6stream7openssl14OpenSSLContext6__ctorMFE4vibe6stream3tls14TLSContextKindE4vibe6stream3tls10TLSVersionZC4vibe6stream7openssl14OpenSSLContext in libvibe-d.a(openssl_4273_569.o)
  "_TLSv1_2_server_method", referenced from:
      _D4vibe6stream7openssl14OpenSSLContext6__ctorMFE4vibe6stream3tls14TLSContextKindE4vibe6stream3tls10TLSVersionZC4vibe6stream7openssl14OpenSSLContext in libvibe-d.a(openssl_4273_569.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1
dmd failed with exit code 1.
```

**Comment by GayDragon** [comment]
vibe.d seems to require an updated version of the openssl library since 0.7.26. 

You can install it with homebrew (`brew install openssl`), and either link it using `brew link openssl --force` (not recommended), or tell dub/dmd to use brew's version in `/usr/local/Cellar/openssl<version>/lib/`.

**Comment by MartinNowak** [comment]
You could prolly also just install the optional botan dependency, though I'm not sure how well it's tested.

**Comment by yannick** [comment]
adding ```-L-L/usr/local/Cellar/openssl/1.0.2d_1/lib``` to dmd.conf solves it.

imho it's  a common scenario for mac users and it should work "out of the box".
where would be the right place to fix this?

**Comment by s-ludwig** [comment]
I've change the code to a hopefully equivalent form that uses numeric flags instead of relying on those functions. Haven't tested on Mac OS, yet.

**Comment by yannick** [comment]
Building vibe-d 0.7.26-beta.1+commit.2.g700aa8c configuration "libevent"...
works! thanks
