### ISSUE TITLE
default install not starting

### ISSUE THREAD

**Issue by claudiug** [rejectedsoftware/vibe.d#1302]
Hi guys

using latest d version with default compiler and latest vide.d version I'm trying to start the app but fails.

Is a new fresh app, without any code

Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/claudiug/.dub/packages/local-packages.json
Note: Failed to determine version of package dlangbyexample at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/claudiug/.dub/packages/local-packages.json
Found dependency vibe-d 0.7.25
Found dependency libevent 2.0.1+2.0.16
Found dependency libev 5.0.0+4.04
Found dependency openssl 1.1.4+1.0.1g
Found dependency libasync 0.7.5
Found dependency memutils 0.4.1
Checking for missing dependencies.
Using fixed selection vibe-d 0.7.25
Using fixed selection libevent 2.0.1+2.0.16
Using fixed selection libev 5.0.0+4.04
Using fixed selection openssl 1.1.4+1.0.1g
Using fixed selection libasync 0.7.5
Using fixed selection memutils 0.4.1
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /Users/claudiug/.dub/packages/local-packages.json
Found dependency vibe-d 0.7.25
Found dependency libevent 2.0.1+2.0.16
Found dependency libev 5.0.0+4.04
Found dependency openssl 1.1.4+1.0.1g
Found dependency libasync 0.7.5
Found dependency memutils 0.4.1
Checking for upgrades.
Using cached upgrade results...
Generating using build
Generate target dlangbyexample (executable /Users/claudiug/personal/d-projects/dlangbyexample/dlangbyexample dlangbyexample)
Generate target vibe-d (staticLibrary /Users/claudiug/.dub/packages/vibe-d-0.7.25 vibe-d)
Generate target libevent (sourceLibrary /Users/claudiug/.dub/packages/libevent-2.0.1_2.0.16 libevent)
Generate target openssl (sourceLibrary /Users/claudiug/.dub/packages/openssl-1.1.4_1.0.1g openssl)
Performing "debug" build using dmd for x86_64.
vibe-d 0.7.25: target for configuration "libevent" is up to date.
Using existing build in /Users/claudiug/.dub/packages/vibe-d-0.7.25/.dub/build/libevent-debug-posix.osx-x86_64-dmd_2068-6E9CB8FC1BE7203F06553556F791A0C3/.
Copying target from /Users/claudiug/.dub/packages/vibe-d-0.7.25/.dub/build/libevent-debug-posix.osx-x86_64-dmd_2068-6E9CB8FC1BE7203F06553556F791A0C3/libvibe-d.a to /Users/claudiug/.dub/packages/vibe-d-0.7.25
Target '/Users/claudiug/personal/d-projects/dlangbyexample/dlangbyexample/.dub/build/application-debug-posix.osx-x86_64-dmd_2068-D2F64B20CC10489E83578E3E0F20D0F3/dlangbyexample' doesn't exist, need rebuild.
dlangbyexample ~master: building configuration "application"...
Using pkg-config to resolve library flags for libssl, libcrypto.
Using direct -l... flags for event, event_pthreads.
dmd -c -of.dub/build/application-debug-posix.osx-x86_64-dmd_2068-D2F64B20CC10489E83578E3E0F20D0F3/dlangbyexample.o -debug -g -w -version=VibeDefaultMain -version=VibeLibeventDriver -version=Have_dlangbyexample -version=Have_vibe_d -version=Have_libevent -version=Have_openssl -Isource/ -I../../../../.dub/packages/vibe-d-0.7.25/source/ -I../../../../.dub/packages/libevent-2.0.1_2.0.16 -I../../../../.dub/packages/openssl-1.1.4_1.0.1g -Jviews source/app.d ../../../../.dub/packages/vibe-d-0.7.25/source/vibe/appmain.d -vcolumns
Linking...
dmd -of.dub/build/application-debug-posix.osx-x86_64-dmd_2068-D2F64B20CC10489E83578E3E0F20D0F3/dlangbyexample .dub/build/application-debug-posix.osx-x86_64-dmd_2068-D2F64B20CC10489E83578E3E0F20D0F3/dlangbyexample.o ../../../../.dub/packages/vibe-d-0.7.25/libvibe-d.a -L-lssl -L-lcrypto -L-lz -L-lcrypto -L-lz -L-levent -L-levent_pthreads -g
ld: library not found for -levent
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2068-D2F64B20CC10489E83578E3E0F20D0F3/ dlangbyexample executable
dmd failed with exit code 1.

**Comment by etcimon** [comment]
Looks like you're on a mac ? You can try `brew install libevent` to fix the linker error

**Comment by s-ludwig** [comment]
You still need to install libevent. Instructions using homebrew: https://github.com/rejectedsoftware/vibe.d#additional-setup-on-mac-using-brew

Alternatively, you could edit dub.sdl and add `subConfiguration "vibe-d" "libasync"` (or in case of dub.json: `"subConfigurations": {"vibe-d": "libasync"}`. This will use the new pure D event abstraction layer, which should by now be reasonably stable, too.

**Comment by s-ludwig** [comment]
That was close ;)

**Comment by claudiug** [comment]
guys, is fix :) +1

thx for the quick help, and sorry :+1:
