### ISSUE TITLE
dub test fails

### ISSUE THREAD

**Issue by rwhite226** [rejectedsoftware/vibe.d#1310]
With my current project 'dub test' with vibe v0.7.25 passes 
But with the new v0.7.26-beta.1 'dub test' fails with
../../../../../tmp/dub_test_root-f035dc5c-69b6-464f-a027-658a95093915.d(17,12): Error: only one main allowed

The contents of said file are here http://pastebin.com/URfR3Evg

**Comment by Geod24** [comment]
You need to put `VibeCustomMain` in your version, or remove your main (as in unittests, it does exactly what you [expect it to](https://github.com/rejectedsoftware/vibe.d/blob/ba160861ab135ed6cf9d06bcee8756d632f0ce51/source/vibe/appmain.d#L39)).

**Comment by rwhite226** [comment]
My app doesn't have a main. My dub.json is
```json
{
	"name" : "graphalyzer-server",
	"description" : "May1618 server backend.",
	"dependencies": {
		"vibe-d": "~>0.7.26-beta.1"
	},
	"versions": ["VibeDefaultMain"]
}

**Comment by Geod24** [comment]
The pastebin you posted has one. 

```D
 void main() { writeln("All unit tests have been run successfully."); }
```

**Comment by rwhite226** [comment]
It appears that it is automatically generated by [dub.](https://github.com/D-Programming-Language/dub/blob/73b4d272ccfe9fa985961b3af9948718e2d10809/source/dub/dub.d#L412)

**Comment by dariusc93** [comment]
You can remove the main since you dont need it.

**Comment by rwhite226** [comment]
@dariusc93 This is only for running the unittests. Simply running my app (dub build and dub run) works fine with either version, but when running the unittests (dub test) v25 passes and v26 fails. Since dub is generating that file with the main for both version it must be something on vibe.d end that broke it.

**Comment by s-ludwig** [comment]
The problem is that the `"versions": ["VibeDefaultMain"]` applies to all (implicitly generated) configurations, including the "library" one that is used as the basis for the unit test build. Defining explicit configurations should work:
```
{
    ...,
    "configurations": [
        {
            "name": "application",
            "targetType": "executable",
            "versions": ["VibeDefaultMain"]
        },
        {
            "name": "library"
        }
    ]
}
```

This is a kind of annoying issue, so any idea for better semantics would be welcome.

**Comment by rwhite226** [comment]
@s-ludwig Thanks that fixed it.

**Comment by jacob-carlborg** [comment]
I hit the same issue today. A couple of ideas:

1. Only use `VibeDefaultMain` when `version(unittest)` is not set
2. Generate the correct dub.json/sdl file when running `dub init -t vibe.d`
