### ISSUE TITLE
mongo.collection.insert: how do you get the id of the inserted element?

### ISSUE THREAD

**Issue by dhasenan** [rejectedsoftware/vibe.d#1370]
The documentation doesn't say how to get the generated ID of a document you just inserted. I got lost in the middle of serialization code trying to determine whether the _id field of a BSON document that I save would be propagated back to the calling code.

The documentation should say explicitly either:

    If you need the IDs of the inserted documents, set the _id field to a BsonObjectID before calling insert().

or:

    If you save a BSON document or a collection of BSON documents, each saved document will have its _id field set to the BsonObjectID of the saved document.

I'm not sure which is correct. I think it's the former but I can't say for sure.

**Comment by s-ludwig** [comment]
Yes, it's the former. Otherwise the server will generate the `_id` field automatically, but won't send it back to the client. It definitely can't hurt to document this explicitly, although it has to be said that this is standard MongoDB behavior and as such is also documented in their docs.
