### ISSUE TITLE
Segfault in module destructor

### ISSUE THREAD

**Issue by yazd** [rejectedsoftware/vibe.d#1374]
This code segfaults:
```
import std.parallelism;     /// import 1
import vibe.d;              /// import 2

void main()
{
    auto t = new TaskPool();
    t.isDaemon = true;
}
```
The segfault is in core.d:1510, `static ~this()`, `st_threadsSignal.emit();` line.
If you change the import order, the segfault doesn't happen.
I realize that it is preferable to not mix `vibe.d` and `std.parallelism`, but the user of `std.parallelism` is a library that should work with and without vibe.d.

Running vibe.d 0.7.26 or vibe.d 0.7.27-alpha.3, dmd v2.069.2, linux x86-64.

**Comment by s-ludwig** [comment]
Looks like strange behavior on part of Druntime. What happens is that `shared static ~this` gets called *before* `static ~this` of the threads created by the task pool. The only "fix" that I see would be to detect this case and skip any per-thread cleanup in that case.

**Comment by yazd** [comment]
If that is the case, it is a bug in druntime. The order is defined here: http://dlang.org/spec/module.html#staticorder

> Shared static constructors on all modules are run before any static constructors.

and

> Shared static destructors are executed after static destructors. 

I'll try producing a minimal testcase and report the bug.

**Comment by yazd** [comment]
Reported here: https://issues.dlang.org/show_bug.cgi?id=15622

**Comment by s-ludwig** [comment]
Ah nice, I looked for an explicit statement, but missed that part, so I wasn't sure.
