### ISSUE TITLE
Possibility to specify interface/IP for outgoing (HTTP) connections.

### ISSUE THREAD

**Issue by japplegame** [rejectedsoftware/vibe.d#1389]
We need something like curl --interface option:
> --interface [name]
> Perform an operation using a specified interface. You can enter interface name, IP address or host name. An example could look like:
> curl --interface eth0:1 http://www.netscape.com/`

And we are willing to pay for it.

**Comment by s-ludwig** [comment]
Do you need to specify an interface name, or would specifying the IP address of the interface be sufficient? If you need a fast solution, best get in touch with me via sludwig@rejectedsoftware.com, I'm currently (as nearly always) overloaded with urgent and semi-urgent issues.

**Comment by japplegame** [comment]
IP address would be sufficient.
