### ISSUE TITLE
https_server_sni example doesn't use TLSContextKind.serverSNI

### ISSUE THREAD

**Issue by csmith1991** [rejectedsoftware/vibe.d#1405]
I'm hoping this is perhaps an oversight, but the [example](https://github.com/rejectedsoftware/vibe.d/blob/master/examples/https_server_sni/source/app.d) looks like it'd have me duplicating code quite extensively.

I'm looking through the source and I don't see an example for [`sniCallback`](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/stream/tls.d#L246). Any help using this would be greatly appreciated.

Thanks!

**Comment by s-ludwig** [comment]
The HTTP server automatically creates an SNI context if multiple different SSL contexts are used on the same interface/port. We should probably have an additional RAW SNI example, though. The corresponding place in the source code is [here](https://github.com/rejectedsoftware/vibe.d/blob/3d851408a813523b73a003805a58f5c5f14c53aa/source/vibe/http/server.d#L1455) and [here](https://github.com/rejectedsoftware/vibe.d/blob/3d851408a813523b73a003805a58f5c5f14c53aa/source/vibe/http/server.d#L1439).

**Comment by csmith1991** [comment]
Gotcha, so I tried the example that you have there, but it seems to be silently crashing IIS on Azure, and if I try to restart it I get a message saying that HTTP_PLATFORM_PORT isn't set.

**Comment by s-ludwig** [comment]
Hum, I'm not familiar with Azure, is IIS set up as a reverse proxy?

**Comment by csmith1991** [comment]
To be specific, I'm using their [web app service](https://azure.microsoft.com/en-us/services/app-service/web/).  I think it might be one? I'm not sure where, or even how to verify.

FWIW, I was able to get SSL working with it, and my browser says its a valid certificate. I just wasn't sure if I'd be able to open a secure websocket without a TLSContext first. Admittedly I haven't tried yet though.

**Comment by csmith1991** [comment]
It appears to be unrelated to what I thought it was. I went ahead and tried to bind a single host, and that's failing, so I must be doing something wrong with sslContext unfortunately. Anyways, this is a separate issue it looks like.

**Comment by s-ludwig** [comment]
Hm, CGI applications sounds like IIS expects the app to talk CGI over stdout/stdin instead of HTTP over TCP. Could that be? vibe.d currently doesn't have a CGI or FastCGI module, but if Azure assumes that, it might make sense to offer one.

**Comment by csmith1991** [comment]
I think I just have it mis-configured somewhere, but not able to figure out with what. I can get it to run with vibe.d via http, its just adding https messes things up. It uses stdout for log files though.

For reference, I'm trying to use [this](http://www.iis.net/learn/extensions/httpplatformhandler/httpplatformhandler-configuration-reference), and it appears some people have gotten this with ASP.Net too.

Under processPath, it says it's listening for HTTP requests, I wonder if that means it won't support TLS.

I'll probably make a tutorial once I get things working.
