### ISSUE TITLE
Can't build under DMD 2.070

### ISSUE THREAD

**Issue by bubnenkoff** [rejectedsoftware/vibe.d#1409]
I am getting next error: http://img.ctrlv.in/img/16/02/09/56b99f90171ea.png

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/02/09/56b9a5441fa84.png

**Comment by bubnenkoff** [comment]
I still can't build it. It's produce a lot of warnings and then this ^

**Comment by s-ludwig** [comment]
Can you try to `dub build --force`? It works for me, at least when I build the examples. I'll have a look at the deprecation warnings before tagging the release, but they shouldn't be responsible for any errors.
