### ISSUE TITLE
calling runEventLoop from a thread doesn't work

### ISSUE THREAD

**Issue by timotheecour** [rejectedsoftware/vibe.d#1414]
can we only call runEventLoop from the main thread?
this causes a problem when another application also requires to be started in the main thread

**Comment by s-ludwig** [comment]
It generally should work in any thread. This is done for the worker thread pool, as well for example the `vibe.stream.stdio.StdFileStream` wrapper. What issues did you encounter?

**Comment by s-ludwig** [comment]
Closing this under the assumption that this was some application specific issue. Please, reopen if this is not the case.
