### ISSUE TITLE
REST: Serializing the entire body into one parameter

### ISSUE THREAD

**Issue by wilzbach** [rejectedsoftware/vibe.d#1422]
Hey I am just getting started with vibe.d, however I am struggling with this issue.

Let's say I have a more complex `FooObject` that my API expects. Is there an easy way to teach the REST API to accept a request body that is the entire object like `{"a": "foo", "b": "bar"}` for the example below?
In other words I would like to serialize the body into one attribute.

I know that [best practices](http://jsonapi.org/format/#crud), but this is possible in most REST frameworks I have worked with and the still the default setting for most JS REST libs.

```
struct FooObject{
    string  a;
    string  b;
}
interface Example4API
{
    int createFoo(FooObject whole_body);
}
class Example4 : Example4API
{
    override:
            int createFoo(FooObject whole_body){
                    return 1;
            }

}
```

**Comment by GayDragon** [comment]
Workaround (not my work, obviously):
https://gist.github.com/yannick/ffa037b2338f95f65e4e

**Comment by wilzbach** [comment]
duplicate of https://github.com/rejectedsoftware/vibe.d/issues/1549
