### ISSUE TITLE
udp.recv(3.seconds) didn't throw exception and wait forever

### ISSUE THREAD

**Issue by mzfhhhh** [rejectedsoftware/vibe.d#1429]
my app  need wait several seconds to check data arrived,buf "udp.recv(3.seconds)" doesn't work and wait forever 

vibe 0.7.27 demo
```D
shared static this()
{
	runTask({
		auto udp_listener = listenUDP(1234);
		while (true) {
			logInfo("waiting...");
			auto pack = udp_listener.recv(3.seconds);
			logInfo("Got packet: %s", cast(string)pack);
		}
	});
}
```

**Comment by mzfhhhh** [comment]
i add this line in "libevent2.d" line1013,and then it's working 
```D
m_driver.m_timers.getUserData(tm).owner = Task.getThis();
```

**Comment by s-ludwig** [comment]
You are right, your code should be used instead of the `acquireTimer` call - I obviously confused that with the `acquire()` calls that are used in other places to set the owner. I'll create a test and add the fix.
