### ISSUE TITLE
Memory Error in vibe.utils.memory / FreeListRef: Refcount is stored outside allocated Memory

### ISSUE THREAD

**Issue by tosttost** [rejectedsoftware/vibe.d#1432]
I discovered this issue while using valgrind. On serving a file using serveStaticFile valgrind reports an invalid read of size 4 whenever the refcount of a FreeListRef is accessed.

I read the source code. It seems that the "+ int.sizeof" to allocate memory for storing ref count got lost with commit 6be547148f45f47020c516b5ac25283734a99d76 .
As far as I figured out:

* the memory for FreeListRef is allocated by calling FreeListObjectAlloc

* FreeListObjectAlloc allocates AllocSize!T bytes (line 639 / 616)

* AllocSize is just the size of T (or the classInstanceSize if T is a class), so no memory for storing the refcount is allocated (line 672)

I have no time to figure out where the "+ int.sizeof" fits best (and therefore, can't create a PR). 

Valgrind output:
==5411== Invalid write of size 4
==5411== at 0xC97B52: D4vibe5utils6memory110T11FreeListRefTS4vibe4core6stream12OutputStream12writeDefaultMFC4vibe4core6stream11InputStreammZ6BufferVbi0Z11FreeListRef11T6opCallZ6opCallFNbZS4vibe5utils6memory110T11FreeListRefTS4vibe4core6stream12OutputStream12writeDefaultMFC4vibe4core6stream11InputStreammZ6BufferVbi0Z11FreeListRef (../../.dub/packages/vibe-d-0.7.27/source/vibe/utils/memory.d:694)<br>==5411== Address 0x1899e270 is 0 bytes after a block of size 65,552 alloc'd<br>==5411== at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreloadmemcheck-amd64-linux.so)
==5411==
==5411== Invalid read of size 4
==5411== at 0xC97AC2: D4vibe5utils6memory110T11FreeListRefTS4vibe4core6stream12OutputStream12writeDefaultMFC4vibe4core6stream11InputStreammZ6BufferVbi0Z11FreeListRef15checkInvariantsMxFNaNbNiZv (../../.dub/packages/vibe-d-0.7.27/source/vibe/utils/memory.d:753)<br>==5411== Address 0x1899e270 is 0 bytes after a block of size 65,552 alloc'd<br>==5411== at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreloadmemcheck-amd64-linux.so)
==5411==
==5411== Invalid read of size 4
==5411== at 0xC97988: D4vibe5utils6memory110T11FreeListRefTS4vibe4core6stream12OutputStream12writeDefaultMFC4vibe4core6stream11InputStreammZ6BufferVbi0Z11FreeListRef5clearMFNbNiZv (../../.dub/packages/vibe-d-0.7.27/source/vibe/utils/memory.d:732)<br>==5411== Address 0x1899e270 is 0 bytes after a block of size 65,552 alloc'd<br>==5411== at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreloadmemcheck-amd64-linux.so)
==5411==
==5411== Invalid read of size 4
==5411== at 0xC9798A: D4vibe5utils6memory110T11FreeListRefTS4vibe4core6stream12OutputStream12writeDefaultMFC4vibe4core6stream11InputStreammZ6BufferVbi0Z11FreeListRef5clearMFNbNiZv (../../.dub/packages/vibe-d-0.7.27/source/vibe/utils/memory.d:732)<br>==5411== Address 0x1899e270 is 0 bytes after a block of size 65,552 alloc'd<br>==5411== at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreloadmemcheck-amd64-linux.so)

**Comment by s-ludwig** [comment]
Thanks for taking this to GitHub. I saw the thread on the forum, but didn't manage to look into it, yet.

I'll make a quick bugfix release soon.
