### ISSUE TITLE
REST multiple UDAs getting mixed up in latest vibe 0.7.27

### ISSUE THREAD

**Issue by rjmcguire** [rejectedsoftware/vibe.d#1437]
@headerParam("session_id", "session_id")
	@bodyParam("submittedContact", "contact")
	Contact postContact(string session_id, Json submittedContact);
 For the interface above I am getting the error:
Expected valid JSON token, got 'VHY1ibu8D-bN'.

Which is the beginning of the session id that I'm passing in via the header parameter. It was working in previous releases of vibe.

Is there any known work-around?

**Comment by rjmcguire** [comment]
I've just tested with 0.7.25 again and it works correctly even if I use same compiler 2.070 (had to catch some exceptions around synchronized for the nothrow errors).

**Comment by s-ludwig** [comment]
I haven't been able to reproduce this. This gist passes for me: https://gist.github.com/s-ludwig/a5d234dd1721449e5b85

Can you confirm this locally and possibly create a failing test case?

**Comment by GayDragon** [comment]
This is actually the same issue as I fixed here.
Filter names (GenCmp, `"Loop" ~ n`) got kept from previous methods while looping through an interface, fix is to simply include the function's name in the Filter name
https://github.com/rejectedsoftware/vibe.d/pull/1453

**Comment by rjmcguire** [comment]
thanks!
