### ISSUE TITLE
performBasicAuth: plz separate "Authorization" header read code and other stuff

### ISSUE THREAD

**Issue by denizzzka** [rejectedsoftware/vibe.d#1449]
Two performBasicAuth functions contain code duplication and also without separate header read function it isn't possible to check auth data without different response cases.

(Faced out with it because I am writing server what uses auth info as parameter, but response isn't depends from availability of auth info.)

**Comment by eco** [comment]
To rephrase it a little based on the conversation we are having in IRC I believe what is being asked for is to support optional verification of an auth request. For example, only requiring an auth request based on other factors of the request (such as what parameters are given). So basically something like `enforceHTTP(/*some criteria that makes it require auth */ && checkAuth(req), HTTPStatus.forbidden);`
