### ISSUE TITLE
@method(HTTPMethod.GET) void fun(int a){} returns 404 after being called

### ISSUE THREAD

**Issue by timotheecour** [rejectedsoftware/vibe.d#1466]
(using registerWebInterface)

workaround: return `Json.emptyObject`
but IMO it shouldn't return 404 when the method returns void

**Comment by s-ludwig** [comment]
That's the universal behavior of the HTTP server system, meant for supporting fall-through request handlers. You have to write a response body of some sort. But leaving fall-through aside, the server has to respond with *something*. 404 or 500 seem to be the only sensible choices.
