### ISSUE TITLE
vibed res ignore POST parameters

### ISSUE THREAD

**Issue by bubnenkoff** [rejectedsoftware/vibe.d#1485]
[Here](https://github.com/ikod/dlang-requests/commit/931b06bedc0b19f8ced8bdb37d81fe3648436e2c) is fix from dlang-requests lib. Look like vibed have same issue. New version of dlang-requests solve problem, but vibed still do not work.

Here is my post from SO:

//-------------------------------------------------------------------------------------------------
I need to get JSON data from one URL and resend it to another URL (to collection of ArangoDB).

I have got next code:

```
void questions(HTTPServerRequest req, HTTPServerResponse res)
{
    Json questions = req.json;
    res.writeBody("Hello, World!", "text/plain");  // need make normal answer

    sendQuestionsToArangoDB(questions); // send data to ArangoDB

}


void sendQuestionsToArangoDB(Json questions)
{

    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // ArangoDB collection

    requestHTTP(collectionUrl,
        (scope req) {
            req.method = HTTPMethod.POST;   
            req.writeJsonBody(questions);
        },
        (scope res) {
            logInfo("Response: %s", res.bodyReader.readAllUTF8());
        }
    );

    writeln("SENDED");

}
```

But I am getting next error:

`Response: {"error":true,"errorMessage":"invalid document type","code":400,"errorNum":1227}`

What I am doing wrong?

Also I tried to use [dlang-request](https://github.com/ikod/dlang-requests) lib.

```
void sendQuestionsToArangoDB(Json questions)
{

    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // collection url

    auto rq = Request();
    rq.verbosity = 2;
    auto rs = rq.post(collectionUrl, `{"a":"b", "c":[1,2,3]}`, "application/json");

    writeln("SENDED");

}
```

Output is next:

> POST /_db/onlinetest/_api/document/ HTTP/1.1
> Content-Length: 22
> Connection: Close
> Host: localhost:8529
> Content-Type: application/json
> 
> < HTTP/1.1 400 Bad Request
> < Server: ArangoDB
> < Connection: Close
> < Content-Type: application/json; charset=utf-8
> < Content-Length: 134
> < 134 bytes of body received
> SENDED

Here is ArangoDB http [docs](https://docs.arangodb.com/HttpDocument/WorkingWithDocuments.html).
//-------------------------------------------------------------------------------------------------

**Comment by s-ludwig** [comment]
I think you'll have the best chances of getting a satisfying answer asking it in the ArangoDB community. The vibe.d side at least looks fine as far as I can tell, as well as the dlang-requests version. The error message appears to be about something within the JSON document itself (an example reason I found was omitting graph specific fields when inserting into a graph collection).

**Comment by s-ludwig** [comment]
Closing for now. If this indeed turned out to be an issue within vibe.d itself, please reopen.
