### ISSUE TITLE
ConnectWebSocket impossible

### ISSUE THREAD

**Issue by Ogromny** [rejectedsoftware/vibe.d#1494]
When I want to create a new WebSocket

```d
WebSocket ws = connectWebSocket(URL("http://localhost:8080/ws"));
```

I get this error:

```bash
Error: function expected before (), not URL of type string
```

**Comment by s-ludwig** [comment]
The error message sounds like a local symbol resolution issue. Do you have anything defined in your code that is also named "URL"? You could try to use `.URL("http...")` or `vibe.inet.url.URL("http...")` to explicitly reference the vibe.d symbol.

**Comment by Ogromny** [comment]
oh yes, 
I have an enum named URL,

It's work now !

Thanks :D
