### ISSUE TITLE
Get a websocket throw a get

### ISSUE THREAD

**Issue by Ogromny** [rejectedsoftware/vibe.d#1495]
How i can do for get a websocket throw a get method ?

```d
class WI
{
    public:
        @method (HTTPMethod.GET) @path ("/") void
        index (HTTPServerResponse response)
        {
            WebSocket ws = ???
        }
}
```

Thanks in advance :D

PS: I'm French sorry for my bad english :/

**Comment by s-ludwig** [comment]
The easiest way is to simply put it as a parameter: `void index(scope WebSocket ws) { ... }` `registerWebInterface` will automatically detect that and establishes a web socket connection. If you want to do it manually instead, you'll have to use a closure and `handleWebSocket`:
```
void index(HTTPServerRequest request, HTTPServerResponse response)
{
    import vibe.http.websockets : handleWebSocket;
    handleWebSocket((scope ws) {
        ...
    }, request, response);
}

**Comment by s-ludwig** [comment]
Closing for now. Please feel free to reopen!
