### ISSUE TITLE
Probleme websocket

### ISSUE THREAD

**Issue by Ogromny** [rejectedsoftware/vibe.d#1498]
Hi,

I have this:

```d
        @method (HTTPMethod.GET) @path ("/") void
        index (HTTPServerResponse response, scope WebSocket socket)
        {
            renderTemplate (response, "index", new Context);
        }
```

and when i execute this i get this:
> WebSocket endpoint only accepts "Connection: upgrade" requests.

What is the probleme ?

Thanks, in advance.

Ps: I'm French sorry for my bad english :(

**Comment by yannick** [comment]
did you check out and run the projects in the example directory?
check e.g. https://github.com/rejectedsoftware/vibe.d/blob/master/examples/websocket/source/app.d#L16   for how websockets work

**Comment by Ogromny** [comment]
Yes i have check this but,

I dont know why i have this error

**Comment by s-ludwig** [comment]
"Connection: upgrade" is how WebSockets generally work - the existing HTTP connection gets reused for WebSocket communications and cannot be used for normal HTTP requests/responses anymore. You'll have to define separate endpoints for the `WebSocket` and for rendering the page.

**Comment by s-ludwig** [comment]
Same here, feel free to reopen if you have more questions!
