### ISSUE TITLE
Deadlock in TaskPipe

### ISSUE THREAD

**Issue by Andrepuel** [rejectedsoftware/vibe.d#1501]
The first thing that is done inside the critical session of the write method of TaskConditionImpl is checking if it will have to signal, i.e. if the buffer was empty. If the buffer is full, there is no need to signal and the fiber will wait until there is free space. It is possible that when the fiber returns from the condition, the buffer is empty already but the need_signal flag will be false. The flag should be checked again after waking up from the condition.

	/** Writes the given byte array to the pipe.
	*/
	void write(const(ubyte)[] data)
	{
		while (data.length > 0){
			bool need_signal;
			synchronized (m_mutex) {
				if (m_buffer.empty) need_signal = true;
				else if (m_growWhenFull && m_buffer.full) {
					size_t new_sz = m_buffer.capacity;
					while (new_sz - m_buffer.capacity < data.length) new_sz += 2;
					m_buffer.capacity = new_sz;
				} else while (m_buffer.full) m_condition.wait();
				auto len = min(m_buffer.freeSpace, data.length);
				m_buffer.put(data[0 .. len]);
				data = data[len .. $];
			}
			if (need_signal) m_condition.notifyAll();
		}
		if (!m_growWhenFull) vibe.core.core.yield();
	}

The exact scenario that I have that reproduces the issue is:

Thread A is going to write 2100 bytes. The buffer size of the TaskPipe is 2048 bytes. Thread B is reading the buffer.
1. Thread A starts writing in the buffer until the buffer fills up.
2. Thread A waits on the condition with need_signal false.
3. Thread B starts reading, on the first read, it notifies the condition because the buffer is not filled up anymore.
4. Note that even signalled, thread A did not wake yet.
5. Thread B keeps on reading until the buffer is empty. Then it will wait on the condition because the buffer is empty.
6. Thread A wakes, the buffer is empty but the need_signal is false.
7. Thread A finishes writing without filling the buffer.
8. Thread B is still waiting on the condition.

My suggestion is putting the `need_signal = m_buffer.empty;` right after the condition. In both the read and the write methods.

**Comment by s-ludwig** [comment]
Agreed. I'll commit a fix right away.
