### ISSUE TITLE
default application does not link with dub test

### ISSUE THREAD

**Issue by georgi-d** [rejectedsoftware/vibe.d#1512]
Hi,

I am using
vibe-d 0.7.28
dmd-2.071.0
dub-0.9.25

Executing the steps to setup a new vibe-d project

     $ dub init test -n -t vibe.d 
     $ cd test
     $ dub test

I get the following error:

Linking...
.dub/build/application-unittest-linux.posix-x86_64-dmd_2071-B7D1B9BF22DA358F2F54D0033CAE17B7/unitestmultimain.o:(.data._D49TypeInfo_S3std8typecons15__T8NullableTiZ8Nullable6__initZ+0x28): undefined reference to `_D3std8typecons15__T8NullableTiZ8Nullable6__initZ'
collect2: ld returned 1 exit status

running:

     $ dub build

or

     $ dub run 

Works fine 

On another sample project `dub test` also failed with an error for duplicate main methods. 
I was able to fix the build error of it by defining CustomMain version on that one.

This is happening on linux.

**Comment by georgi-d** [comment]
This appears to be fixed in latest version of vibe.d

**Comment by ForNeVeR** [comment]
Sorry, but what's the "latest" version? Seems to still happen to me with vibe-d-0.7.28, logs attached: https://travis-ci.org/codingteam/codingteam.org.ru/builds/137167918#L206

**Comment by ForNeVeR** [comment]
Aha, it really was fixed by updating vibe.d to the latest published `0.7.30-alpha.2`. Thanks for the info!
