### ISSUE TITLE
Interactive init always generates source/app.d file

### ISSUE THREAD

**Issue by schveiguy** [rejectedsoftware/vibe.d#1520]
interactive initialization generates source/app.d file. If in the middle of answering the questions, I decide to abort (i.e. ctrl-c), the source/app.d file is still there, and dub init now complains "The target directory already contains a 'source/' file. Aborting." The directory is not in a usable state.

The source directory + app.d file should not be generated until interactive initialization is complete.

**Comment by schveiguy** [comment]
Clarification: NO files should be written until interactive initialization is complete. Not just source/app.d.

**Comment by s-ludwig** [comment]
Moved to the DUB issue tracker.

**Comment by schveiguy** [comment]
Oops! sorry, I meant to put it in dub. I must have had this window open...
