### ISSUE TITLE
Example of mysql ConnectionPool

### ISSUE THREAD

**Issue by shahmuratov** [rejectedsoftware/vibe.d#1528]
Hi everyone! Where can I find example of vibe.d connectionpool used with mysql? Thanks for reply

**Comment by s-ludwig** [comment]
The [mysql-native]() library contains an example: https://github.com/mysql-d/mysql-native/blob/415f53f824907021a0885de3502634753c467bc7/source/app.d#L33

Unfortunately with multiple other code paths mixed, but the only thing that needs to be done is to create a `MysqlDB` instance and use `.lockConnection()` to get an actual connection to work with. RAII will take care of making the connection available for further queries once it goes out of scope.
