### ISSUE TITLE
HTTPServerRequest needs some custom storage

### ISSUE THREAD

**Issue by schveiguy** [rejectedsoftware/vibe.d#1529]
Currently, there is the `params` member, which can store custom strings to be passed through the chain of processors.

However, there are plenty of use cases where I want to store something other than a string in the request data. For instance, I want to store the user id in the session, and early on in the routing, I want to fetch all the information about the user from the database, and store that User object in the request, for further access.

I don't want to cache the user data in the session, since it may change in the DB. And I don't want to fetch that data from the database at every step in the router chain.

What I'm going to do for now, is to use the `params` member, with the value "string" being 0 length and pointing at some object that I really know what it is. And just add casts everywhere.

This should work, but god is it ugly! `HTTPServerRequest` desperately needs some mechanism to store custom types according to an id or string. I understand from searching the forums that this is a recognized problem, and the backwards compatibility requires that we don't muck with how params works. I propose to add a new variable that is a `Variant[string]`, or even `void*[string]`, called `context` or something like this (hell, even if we have a `void * context` member), so that I can simply pass data around.

**Comment by bheads** [comment]
Java has attributes as part of the ServletRequest Spec:

https://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/ServletRequest.html#setAttribute(java.lang.String, java.lang.Object)

This would be a very useful addition!

**Comment by thaven** [comment]
The Variant[string] (or a Variant typed DictionaryList) is probably the most useful. void* would be bad, because it can store only one value, so multiple libraries using it would cause trouble for sure!

**Comment by s-ludwig** [comment]
Fixed by 9d0a75b838b53bf281f21a0dd8209b508a2a0b67.
