### ISSUE TITLE
[quession] when i use vibe.d in my mache some bad thing happend  

### ISSUE THREAD

**Issue by beckbikang** [rejectedsoftware/vibe.d#1531]
dub
Package vibe-d can be upgraded from 0.7.28 to 0.7.29.
Use "dub upgrade" to perform those changes.
Performing "debug" build using dmd for x86_64.
vibe-d:utils 0.7.28: target for configuration "library" is up to date.
vibe-d:data 0.7.28: target for configuration "library" is up to date.
vibe-d:core 0.7.28: target for configuration "libevent" is up to date.
vibe-d:http 0.7.28: target for configuration "library" is up to date.
vibe-d:diet 0.7.28: target for configuration "library" is up to date.
vibe-d:mail 0.7.28: target for configuration "library" is up to date.
vibe-d:mongodb 0.7.28: target for configuration "library" is up to date.
vibe-d:redis 0.7.28: target for configuration "library" is up to date.
vibe-d:web 0.7.28: target for configuration "library" is up to date.
vibe-d 0.7.28: target for configuration "libevent" is up to date.
testjson ~master: building configuration "application"...
Linking...
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libevent_pthreads.so: undefined reference to `evthread_set_condition_callbacks'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libevent_pthreads.so: undefined reference to `event_mm_malloc_'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libevent_pthreads.so: undefined reference to `event_mm_free_'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libevent_pthreads.so: undefined reference to `evthread_set_id_callback'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libevent_pthreads.so: undefined reference to `evthread_set_lock_callbacks'
collect2: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.

**Comment by beckbikang** [comment]
what can i do to fix it ?

**Comment by s-ludwig** [comment]
I'm not sure what exactly goes wrong here, but it looks like maybe the `libevent_pthreads.so` library has a different version than the libevent core library. A way to side-step the whole issue would be to use `libasync` instead of `libevent`. In dub.json that would mean adding `"subConfigurations": {"vibe-d": "libasync"}`, or in dub.sdl `subConfiguration "vibe-d" "libasync"`.

**Comment by beckbikang** [comment]
thanks for your answer.
i will try it .
