### ISSUE TITLE
VibedDefaultMain vs Custom Main behavior

### ISSUE THREAD

**Issue by schancel** [rejectedsoftware/vibe.d#1535]
This is more of a question than an issue (maybe it's an issue).  There seems to be a difference in behavior between implementing your own main function, and using Vibe.d's.  Is this significant -- will it cause bugs?

e.g. my static this() prints "hello world" once, but I get this (presumably because of thread multiplexing in vibed)

```
frontend git:(master) ✗ ./frontend
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
```

If I were to write my own main function which does the same things as `static this()`, and then calls `runEventLoop()` my route registration code would only run once, vs. once for each thread.

Is that important?

Thanks in advance!

**Comment by bheads** [comment]
Probably should be using **shared static this** and not **static this** (https://vibed.org/docs)

**static this** is called for each thread setting up thread local storage: https://dlang.org/spec/class.html#static-constructor

**shared static this** is called once for global storage:
https://dlang.org/spec/class.html#SharedStaticConstructor

**Comment by schancel** [comment]
Ah.  Man, the amount of times shared is used for different things is slightly annoying.  Thanks for the response -- I didn't even notice that the shared keyword was being used.
