### ISSUE TITLE
ServeStaticFiles caching too short

### ISSUE THREAD

**Issue by skoppe** [rejectedsoftware/vibe.d#1558]
The convention on the web for resources that can be cache indefinitely is to put the max age at 1 year.
 
While HTTPFileServerSettings does allow setting the maxAge, it uses a Duration to do so. Since a duration cannot last as long as a year, it is currently not possible to set an indefinite cache age for resources.

Having a indefinite cache age in combination with a cache busting techniques allows a site to maximally leverage the browser's cache and reduce if-modified-since request, thereby speeding up the site (on subsequent visits).

**Comment by skoppe** [comment]
Never mind. One can do:

```
auto fileSettings = new HTTPFileServerSettings();
fileSettings.maxAge = 31536000.seconds;
```

**Comment by s-ludwig** [comment]
Or slightly shorter: `365.days` - `Duration`, AFAIU, just has no `years` constructor, because a year has variable length.

**Comment by skoppe** [comment]
Yep, you are right. I misread the docs.
