### ISSUE TITLE
diet templates in sub directories

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1559]
rather than keep all my diet templates in one directory `/views`, I'm organising them into subdirectories. So all templates to do with my webinterface that handles `mydomain.com/admin` go into `/views/admin` and then I render them by calling: `render!("admin/manageusers.dt", arg1, arg2, etc);`.

This has been fine as I've only been building the project on OSX and Linux (Fedora). Now just started putting in some required changes to build on Windows and am seeing the following error:

```
vibe-d-0.7.30-beta.1\vibe-d\source\vibe\templ\diet.d(255,33): Error: file "admin/manageusers.dt" cannot be found or not in a path specified with -J
```

Changing `render!("admin/manageusers.dt", arg1, arg2, etc);` to `render!("admin\\manageusers.dt", arg1, arg2, etc);` will resolve the issue but having to do:

```D
version(Windows) {
    render!("admin\\manageusers.dt", arg1, arg2, etc);
}
version(Posix) {
    render!("admin/manageusers.dt", arg1, arg2, etc);
}
```

is a little messy. Could the _render_ function be modified to accept a '/' on windows as well as '\\\\'?

**Comment by rikkimax** [comment]
Known bug in dmd, https://issues.dlang.org/show_bug.cgi?id=3420

**Comment by SingingBush** [comment]
ok thanks for letting me know. I'll move all templates into views and use a naming convention for my files instead
