### ISSUE TITLE
Double quotes in multipart request

### ISSUE THREAD

**Issue by JanVana** [rejectedsoftware/vibe.d#1562]
Hello, we have a server implemented using Vibe. We are sending it multi-part requests from .Net, but Vibe can't read any of the uploaded files. Comparing it with the same request created by Firefox, I can see it is missing double quotes around the name and the filename parameters. Manually adding double quotes to the .Net request fixes the issue.

Would it be possible to fix this in Vibe, so that we can send requests from .Net without any hacks?

Incorrectly handled request: [BadRequest.txt](https://github.com/rejectedsoftware/vibe.d/files/474570/BadRequest.txt)
Correctly handled request: [FixedRequest.txt](https://github.com/rejectedsoftware/vibe.d/files/474585/FixedRequest.txt)

**Comment by s-ludwig** [comment]
Fixed by #1725.
