### ISSUE TITLE
mongodb ensureIndex IndexFlags has deprecated naming style

### ISSUE THREAD

**Issue by deviator** [rejectedsoftware/vibe.d#1571]
[`IndexFlags`](http://vibed.org/api/vibe.db.mongo.collection/IndexFlags) has capitalized member names, in all other enums capitalized name style is deprecated (for example [`Bson.Type`](http://vibed.org/api/vibe.data.bson/Bson.Type)). I think it happens because `IndexFlags` stay in `source/db/mongo/collection.d` instead `source/db/mongo/flags.d`.

**Comment by s-ludwig** [comment]
You are right, I've moved it to flags.d now in addition to fixing the naming.
