### ISSUE TITLE
How to create NetworkAddress object?

### ISSUE THREAD

**Issue by FreeSlave** [rejectedsoftware/vibe.d#1575]
How do I manually create NetworkAddress from ip address and port?
Documentation does not list constructor in [NetworkAddress](http://vibed.org/api/vibe.core.net/NetworkAddress)
I want to create NetworkAddress to use in [UDPConnection.send](http://vibed.org/api/vibe.core.net/UDPConnection.send)

**Comment by s-ludwig** [comment]
One way is to set the `.family`, `.sockAddrInet(4/6)` and `.port` properties after creation. The other is to use `resolveHost` with the `use_dns` parameter set to `false`.

**Comment by FreeSlave** [comment]
By documentation sockAddr* properties have only getters and no setters.
resolveHost probably should be mentioned on NetworkAddress doc page. Same goes to listenUDP and UDPConnection. Would make things much easier for novices.

**Comment by s-ludwig** [comment]
Good point, I'll add that to the documentation. Since the `sockAddr` properties return a pointer, it's still possible to change the contents through the getter.

**Comment by s-ludwig** [comment]
Closing for now. Please re-open if you feel anything is missing!
