### ISSUE TITLE
FileDescriptorEvent blocks I/O

### ISSUE THREAD

**Issue by japplegame** [rejectedsoftware/vibe.d#1583]
Looks like FileDescriptorEvent blocks other vibe.d I/O
This code
```d
/+ dub.json:
    {
        "name": "test",
        "dependencies": {
            "vibe-d:core": "0.7.29"
        }
    }
+/

import std.stdio;
import std.socket;
import std.datetime;
import vibe.core.core;

void main() {
    runTask({
        writeln("start task");
        auto pair = socketPair();
        auto evt = createFileDescriptorEvent(pair[1].handle, FileDescriptorEvent.Trigger.any);
        //destroy(evt);
        writeFile("dummy.txt", cast(immutable ubyte[]) "1234567890");
        writeln("end task");
        exitEventLoop();
    });
    runEventLoop();
}
```
prints
```
start task
```
end never exits the event loop.
Looks like task hangs on `writeFile()`.
If to uncomment `destroy(evt)` then code works as expected.

**Comment by s-ludwig** [comment]
For reference: https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/35623/

**Comment by japplegame** [comment]
Turning sockets to a non-blocking mode doesn't help.
```d
...
pair[0].blocking = false;
pair[1].blocking = false;
auto evt = createFileDescriptorEvent(pair[1].handle, FileDescriptorEvent.Trigger.any);
...
```

**Comment by s-ludwig** [comment]
Okay, I'll try to reproduce this tomorrow.

**Comment by s-ludwig** [comment]
The problem turned out to be that libevent looped infinitely in a call to `event_base_loop(m_eventLoop, EVLOOP_NONBLOCK);`, because the file descriptor is in write-ready state, so that every loop iteration fires an event. I'll add `EVLOOP_ONCE` to avoid that.
