### ISSUE TITLE
If using redis can't build with release flag.

### ISSUE THREAD

**Issue by Faianca** [rejectedsoftware/vibe.d#1584]
Vibe version: 0.7.29
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Problem: If using redis can't build with release flag. ( running just dub works fine )
Happens with the webchat-tutorial as well. 

`git clone https://github.com/rejectedsoftware/webchat-tutorial  && cd webchat-tutorial`

`dub build --config=application --build=release`

`.dub/build/application-release-linux.posix-x86_64-dmd_2071-998A2124F13E0945199BD2914D2F9D83/webchat.o: In function `_D4vibe4core14connectionpool61__T16LockedConnectionTC4vibe2db5redis5redis15RedisConnectionZ16LockedConnection10__postblitMFNbZv':
../../.dub/packages/vibe-d-0.7.29/vibe-d/source/vibe/appmain.d:(.text._D4vibe4core14connectionpool61__T16LockedConnectionTC4vibe2db5redis5redis15RedisConnectionZ16LockedConnection10__postblitMFNbZv+0x69): undefined reference to `_D4vibe4core3log184__T8logTraceVAyaa74_2e2e2f2e2e2f2e6475622f7061636b616765732f766962652d642d302e372e32392f766962652d642f736f757263652f766962652f636f72652f636f6e6e656374696f6e706f6f6c2e64Vii123TAyaTPvTiZ8logTraceFNbNfAyaLPvLiZv'
collect2: error: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.
`

**Comment by s-ludwig** [comment]
Did you try to perform a clean build (i.e. `dub build -b release --force`)? I tried to reproduce it with the commands above (DMD 2.071.2 and the latest beta, on Linux Mint 18 (based on Ubuntu 16.04) and everything worked flawlessly.

**Comment by Faianca** [comment]
@s-ludwig confirm that --force works T_T.

**Comment by s-ludwig** [comment]
Okay, then it was probably just some intermediate build result left over from an earlier 2.071.x DMD version that didn't mix well.
