### ISSUE TITLE
FIeDescriptorEvent infinitely raises write events on inactive socket.

### ISSUE THREAD

**Issue by japplegame** [rejectedsoftware/vibe.d#1591]
This code prints "write event" infinitely.
```d
import std.stdio;
import std.socket;
import std.datetime;
import vibe.core.core;

void main() {
    runTask({
        writeln("start task");
        auto pair = socketPair();
        pair[1].blocking = false;
        auto evt = createFileDescriptorEvent(pair[1].handle, FileDescriptorEvent.Trigger.write);
        while(true) {
			evt.wait(FileDescriptorEvent.Trigger.write);
			writeln("write event");
			sleep(1.seconds);
		}
    });
    runEventLoop();
}
```
I don't write anything to socket. Why `FileDescriptorEvent` triggers write events and how to avoid this?
PR #763 may be related

**Comment by japplegame** [comment]
Maybe I don't understand something?

**Comment by s-ludwig** [comment]
"Write" event actually means "write-ready", so if no data ever gets written, the FD will stay write-ready indefinitely. A possibility to avoid this would be to make the event edge-triggered, in which case it would only fire once. For normal back-and-forth protocols, this would usually not make a difference, but in other cases that can reduce the overhead. The caveat is that it's then easy to miss an event.

**Comment by japplegame** [comment]
Thanks, I understand. We definitely need something like PR #763.
I'm trying integrate PostgreSQL libpq library and vibe.d core. And now I have to create and destroy FileDescriptorEvent every time at sending query to socket.

**Comment by japplegame** [comment]
Is there a way to temporarily disable write events without destorying FileDescriptorEvent object?

**Comment by japplegame** [comment]
Ok, I create PR #1592
