### ISSUE TITLE
serialize and deserialize with different names

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1600]
**feature request**

I am writing a system that gets some data from a 3rd party REST API which returns in the format:

```json
{
    "Authentication Data": "someUsername",
    "Email Address": "some.email@domain.com"
}
```

So I have a struct that I deserialize this too:

```D
User u = {
    @name("Authentication Data") string username;
    @name("Email Address") string email;
};
```

all works fine. However, the data is then getting returned from my system to a front end that expects:

```json
{
    "username": "someUsername",
    "email": "some.email@domain.com"
}
```

it would be convenient to have my `User` struct only use `@name` when deserializing but not for serialization. Perhaps the option to pass a 2nd parameter to `@name` if it should only be used one way:

```D
User u = {
    @name("Authentication Data", Deserialize) string username;
    @name("Email Address", Deserialize) string email;
};
```

**Comment by SingingBush** [comment]
Not sure if this is the correct way to go about this but after looking through the vibe source I've started doing the following:

```D
struct DESERIALIZE {}

struct User {
    @NameAttribute!DESERIALIZE("Authentication Data") string username;
    @NameAttribute!DESERIALIZE("Email Address") string email;
};
```

**Comment by s-ludwig** [comment]
What you can do is to customize the `@name` attribute for a particular serialization policy (which may be what you are already doing in that last snippet, if you also use `deserializeWithPolicy`):

```
struct ThirdPartyPolicy {}
struct User {
    @name!ThirdPartyPolicy("Authentication Data")
    string username;
}

auto user = deserializeWithPolicy!(JSONStringSerializer, ThirdPartyPolicy, User)(`{"Authentication Data": "foo"}`);
assert(user.username == "foo");
assert(user.serializeToJsonString() == `{"username":"foo"}`);
```
