### ISSUE TITLE
Unable to build vibe-d:http

### ISSUE THREAD

**Issue by Scellow** [rejectedsoftware/vibe.d#1611]
Hello

I'm unable to build it with dmd v2.072.0

Here is my dub.json

```json
	"dependencies" : {
		"vibe-d": "~>0.7.30"
	},
	"subConfigurations": {"vibe-d": "win32"}
```

Here is what i get: 

```
vibe-d:utils 0.7.30: building configuration "library"...
vibe-d:data 0.7.30: building configuration "library"...
vibe-d:core 0.7.30: building configuration "win32"...
vibe-d:http 0.7.30: building configuration "library"...
..\..\AppData\Roaming\dub\packages\vibe-d-0.7.30\vibe-d\source\vibe\http\server.d(1640,32): Error: variable vibe.http.server.handleHTTPConnection.tls_stream variables cannot be of type void
dmd failed with exit code 1.
```

OS: Windows 10 x64

**Comment by Scellow** [comment]
Looks like it fails with GDC too #1602

**Comment by s-ludwig** [comment]
I suspect that this is a DUB issue. It seems like the default openssl dependency is not included in the build. As a workaround, you could try to put the dependency `"openssl": "*"` into your project.

**Comment by s-ludwig** [comment]
BTW, which version does `dub --version` report for you?

**Comment by dhasenan** [comment]
Duplicated with DUB version 1.0.0, built on Jun 20 2016 (Linux x64, sha1 1162ee5611476fb987ce8e138ee65145d5a022b5).

**Comment by dhasenan** [comment]
And confirmed that adding a dependency on openssl fixed it.

**Comment by s-ludwig** [comment]
I've opened a bug on the DUB bug tracker as a replacement for this one: https://github.com/dlang/dub/issues/990

**Comment by kinke** [comment]
I just tested w/ dub v1.1.1-beta.1, and the issue persists.
