### ISSUE TITLE
missing http headers when using requestHTTP with HTTPMethod.POST

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1614]
I'm integrating with a 3rd party REST API and have been getting data with code a little like this:

```D
Json response = requestHTTP(`https://domain.com/someapi/data`,
                (scope req) {
                    req.headers["Accept"] = `application/json`;
                    req.headers["Content-Type"] = `application/json`;
                    req.headers["X-CSRF-Header"] = ``;
                    req.headers["Authorization"] =`Basic blahblahblahblahblahblahblahblahblahblah`;
                }
            ).readJson;
```

everything has been working fine but now I've got to the point that I need to POST data so I wrote some similar code:

```D
Json response = requestHTTP(`https://domain.com/someapi/data`,
                (scope req) {
                    req.method = HTTPMethod.POST;
                    req.writeJsonBody(Json(["key": Json("value")]));
                    req.headers["Accept"] = `application/json`;
                    req.headers["Content-Type"] = `application/json`;
                    req.headers["X-CSRF-Header"] = ``;
                    req.headers["Authorization"] =`Basic blahblahblahblahblahblahblahblahblahblah`;
                }
            ).readJson;
```

but this fails. I was baffled with this as the 3rd party API is responding with a 404 but I know the URL and posted json data is correct as I've tested using some other tools.

Eventually I opened wireshark to take a look at the requests and have found that when doing a GET the headers are fine but when doing a POST the *X-CSRF-Header* and *Authorization* are missing.

**Comment by s-ludwig** [comment]
`writeJsonBody` needs to come after setting the headers. It would be nice to have an assertion that enforces this, but since `headers` is just a dumb map, this is not that straight forward in this case.

**Comment by SingingBush** [comment]
thanks @s-ludwig that solved my problem.
