### ISSUE TITLE
add a pretty print option to RestInterfaceSettings

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1621]
there are functions to get pretty json strings so why not allow an option to have vibe return a pretty json response:

```D
auto settings = new RestInterfaceSettings;
settings.pretty = true; // default would be false
```

**Comment by Geod24** [comment]
IIRC that's the default in `debug` mode:
https://github.com/rejectedsoftware/vibe.d/blob/f74749618701126b26642b4bea0222ccdae9437b/web/vibe/web/rest.d#L1345-L1346 ?

**Comment by SingingBush** [comment]
Isn't that code for rest client? I was meaning server response. I've been doing debug builds, it's the default when using dub.

**Comment by s-ludwig** [comment]
You're right, it was just implemented for the client. The server is now following suit on GIT master.
