### ISSUE TITLE
suppress statusDebugMessage when Exception thrown in REST api

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1623]
if an exception is thrown in the rest interface the following Json is returned:

```
{
    "statusMessage": "An error message, hopefully useful",
    "statusDebugMessage": "bloomin 0x0000000104c2a8c0 big stacktrace of 0x0000000104cc8a3c const(bool function(immutable(char)[], scope bool delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch + 272\n18 meaningless drivel 0xffffffffffffffff 0x0 + 18446744073709551615"
}
```

at times I've managed to get something useful from `statusDebugMessage` but not often. It would be handy to silence it, especially if doing a release build.

So in [/vibe/web/rest.d#L1141-L1144](https://github.com/rejectedsoftware/vibe.d/blob/a9c45acc46242246a68738e3ffc7432a4a0e9b90/web/vibe/web/rest.d#L1141-L1144) where it has:

```D
res.writeJsonBody(
    [ "statusMessage": e.msg, "statusDebugMessage": sanitizeUTF8(cast(ubyte[])e.toString()) ], 
    HTTPStatus.internalServerError
    );
```

How about doing:

```D
debug {
    res.writeJsonBody(
        [ "statusMessage": e.msg, "statusDebugMessage": sanitizeUTF8(cast(ubyte[])e.toString()) ], 
        HTTPStatus.internalServerError
        );
} else {
    res.writeJsonBody(
        [ "statusMessage": e.msg ], 
        HTTPStatus.internalServerError
        );
}
```

**Comment by s-ludwig** [comment]
Sounds reasonable. I would possibly have preferred testing `HTTPServerSettings.options & HTTPServerOption.errorStackTraces` instead, but the REST interface generator doesn't have access to that as it stands. It could still make sense to make this a runtime setting in `RestInterfaceSettings`, though, if there is a need.
