### ISSUE TITLE
readOption bug

### ISSUE THREAD

**Issue by mzfhhhh** [rejectedsoftware/vibe.d#1624]
vibe-d-0.7.30
can't read command param "user"
```D
string user;
string user1;
//app.exe --user=abc --user1=abc
readOption("user",&user,"db user");//err
readOption("user1",&user1,"db user");//ok
writeln(user,",",user1);
```

**Comment by s-ludwig** [comment]
The problem here is that vibe.d already expects a `--user` argument by default (sets the user ID used for privilege lowering), and `readOption` may only be called once per option. You can define the `VibeNoDefaultArgs` version in the package recipe to disable all default options.
