### ISSUE TITLE
Linking error with LDC on Win64 due to strange subpackage libs-ldc

### ISSUE THREAD

**Issue by kinke** [rejectedsoftware/vibe.d#1629]
Testing dub (v1.1) and vibe.d (v0.7.30) with an early LDC 1.1 (https://github.com/ldc-developers/ldc/pull/1891), a project template cannot be linked on Win64 due to missing `z.lib`. This seems to come in via vibe.d's subpackages in `%AppData%\dub\packages\vibe-d-0.7.30\vibe-d\dub.json`, where there's a `"libs-ldc": [ "z" ]` item. Removing it gets the project to compile, link and run successfully, with both LDC2 and LDMD2.

I did a quick test on Ubuntu 16.04 (x86_64), removed the subpackage as well (and worked around #1611 with a manually added OpenSSL dependency), and it's also working. So this LDC-specific dependency (on zlib apparently) may not be required after all (isn't it part of ~~druntime~~ Phobos?) and only causes trouble on Windows.

**Comment by s-ludwig** [comment]
I had to add the explicit dependency a while ago (9df23d49, same was done for GDC: #1607). Did the build succeed on Linux without removing it? If that's the case, I would suggest to change this to `"libs-ldc-posix": ["z"]`, so that older versions of LDC also still work.

**Comment by kinke** [comment]
> Did the build succeed on Linux without removing it?

It did. So your suggested fix makes sense, although zlib should be part of libphobos2-ldc for quite a while now.

**Comment by s-ludwig** [comment]
Okay, I'll change it like that then. Based on the context of my commit, I guess that LDC 1.0.0 was still affected by this, which is still the latest stable release, so I'd like to keep the workaround for a while still.
