### ISSUE TITLE
sendFile should support 206 Partial Content (for media streaming)

### ISSUE THREAD

**Issue by WebFreak001** [rejectedsoftware/vibe.d#1633]
right now when using sendFile to send some kind of video like webm or mp4 if the user wants to seek it will either not seek or reset to the start position because vibe.d sends all data at once. Using Partial Content the client requests only the data it needs. So for example when hosting some kind of 3h movie it won't send everything at once and the user can even pause/play and seek without the video resetting to 00:00.

Only drawback is that only >=HTTP/1.1 compatible clients support this (no HTTP/1.0), but I don't think this is a problem at all in 2016/2017 where HTTP/2 is already out and used.

**Comment by s-ludwig** [comment]
Dup of #716.

**Comment by s-ludwig** [comment]
Should definitely be implemented sooner rather than later.
