### ISSUE TITLE
RestInterface void functions return body

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1638]
my Rest Interface has some void functions. If I do a DELETE request to `/thing/5` it maps through to `void deleteThing(string id)`. Problem is this is returning `{}` which in turn causes problems with the Javascript front end I'm using.

This would've been ok if the function was something like `Json deleteThing(string id)` but when it's return type is void there really shouldn't be any content in the response.

**Comment by s-ludwig** [comment]
The new behavior definitely makes sense, but is potentially a breaking change (the client had to be adjusted to cope with empty response bodies). Hopefully this will not really surface in practice. But a full deprecation path seems like overkill in this case.
