### ISSUE TITLE
Vibe.d status is always beta

### ISSUE THREAD

**Issue by arietto** [rejectedsoftware/vibe.d#1639]
Sorry for disturbing. Could you remove beta label from the [upper banner](https://vibed.org/images/title.png). "Eternal" beta status makes some people think that it is a toy indi project.

**Comment by s-ludwig** [comment]
Will be removed once [vibe-core](https://github.com/vibe-d/vibe-core) is released in version 1.0.0 (should happen around end of January or February next year). All other sub packages will then also start to target a 1.0.0 release.

**Comment by s-ludwig** [comment]
Removed by https://github.com/rejectedsoftware/vibed.org/commit/7d66205daa72553d86cad4d5a31ab26e051a470b (a typo slipped in the commit comment, unfortunately)
