### ISSUE TITLE
Error: variable vibe.http.server.handleHTTPConnection.tls_stream variables cannot be of type void

### ISSUE THREAD

**Issue by bubnenkoff** [rejectedsoftware/vibe.d#1666]
subj

**Comment by s-ludwig** [comment]
There is a workaround in a previous ticket here: https://github.com/rejectedsoftware/vibe.d/issues/1625

Must be some kind of DUB issue, that the optional-default dependency to openssl isn't included for some reason.

**Comment by s-ludwig** [comment]
The code can be changed, though, to at least compile and to only error out at runtime if a TLS connection is actually requested (keeping the other ticket open for that reason).
