### ISSUE TITLE
0.8: alias syntax no longer works for route handlers

### ISSUE THREAD

**Issue by wilburn** [rejectedsoftware/vibe.d#1668]
With Vibe.d 0.7.30 the following handy syntax worked to create handlers:

```d
router.get("/api/login/google", delegate void(scope req, scope res) {
});
```

However with 0.8 one no longer can provide a alias function and needs to do sth. like:

```d
router.get("/api/login/google", delegate void(scope HTTPServerRequest req, scope HTTPServerResponse res) {

});
```

This is due to this change:
https://github.com/rejectedsoftware/vibe.d/commit/2d9967e23e24d2957651bd1228b5360e54ab7a16#diff-36fb55448cf0bde8eba77033436ae3eb

Is there any plan on supporting the convenient alias syntax for routes?
(For `httpRequest` it's still supported.)

**Comment by s-ludwig** [comment]
Fortunately adding an overload beneath the template functions worked without issues. It's now even possible to drop the explicit `delegate void` prefix.
