### ISSUE TITLE
`%2f` interpreted as separator `/` for routing

### ISSUE THREAD

**Issue by BenjaminSchaaf** [rejectedsoftware/vibe.d#1679]
`%2f` is meant to be a literal `/` not as a path separator.

Replacing any `/` with a `%2f` seems to yield the same result.

**Comment by s-ludwig** [comment]
Previous issues: #1628 and #1436

There are two open approaches to fix this: #1635 #1436
I really just need to get my head around how to best approach this (mainly while considering backwards compatibility in a reasonable manner).
