### ISSUE TITLE
Should't writeVoidBody write Content-Length header?

### ISSUE THREAD

**Issue by tchaloupka** [rejectedsoftware/vibe.d#1682]
REST interface was changed by https://github.com/rejectedsoftware/vibe.d/commit/1a082c5104229171a6d2bdbd2e1c610b167e2b82 so that now methods without return value doesn't write empty object.

But when I call such a method with curl, it waits 10 seconds after the request is already processed.
Curl outputs: no chunk, no close, no size. Assume close to signal end

Vibe writes just this headers:
```
HTTP/1.1 200 OK
Server: some server
Date: Tue, 14 Feb 2017 15:38:48 GMT
Keep-Alive: timeout=10
```

So the connection is closed by the timeout.

**Comment by s-ludwig** [comment]
The REST interface shouldn't use `writeVoidBody`, but instead write an empty response. I didn't realize that when making this change. `writeVoidBody` is meant specifically to write no body at all as opposed to an empty body. This is important for certain response codes. It would probably be a good idea to add some rules to catch such issues earlier.
