### ISSUE TITLE
deserializeBson: how to handle field renames (eg for invalid D names)?

### ISSUE THREAD

**Issue by timotheecour** [rejectedsoftware/vibe.d#1683]
@s-ludwig 
suppose collection has a field "version", which is illegal in D, how would i handle this with minimal code?

ideally would be nice to have a method:
```
void postprocessDeserialization(Bson obj){
  version_=obj["version"];
}
```
is that supported?

```
struct User{
  string version_;
  // other fields
}

auto result=collection.find!User([version" : "foo"]);
```

EDIT: sorry it's pretty clear in docs

**Comment by s-ludwig** [comment]
Just in case someone stumbles over this, both `string version_;` (underscore is automatically removed during serialization) and `@name("version") string version_;` work in this case.

BTW, have you seen the former rule mentioned somewhere in the docs? I didn't find it right away, so I'll add a comment in one or two places.
