### ISSUE TITLE
vibe-0.8.*: @safe delegate in Bson's opApply (foreach iterating)

### ISSUE THREAD

**Issue by denizzzka** [rejectedsoftware/vibe.d#1688]
Can not compile code what uses foreach over Bson array elements:

```D
foreach(bElem; bsonArr)
{...}
```

```
../.dub/packages/dpq2-0.6.20/dpq2/src/dpq2/conv/from_bson.d(127,9): Error: none of the overloads of 'opApply' are callable using argument types (int delegate(Bson bElem) @system), candidates are:
../vibe.d/data/vibe/data/bson.d(662,6):        vibe.data.bson.Bson.opApply(scope int delegate(Bson obj) @safe del)
../vibe.d/data/vibe/data/bson.d(678,6):        vibe.data.bson.Bson.opApply(scope int delegate(ulong idx, Bson obj) @safe del)
../vibe.d/data/vibe/data/bson.d(700,6):        vibe.data.bson.Bson.opApply(scope int delegate(string idx, Bson obj) @safe del)
```

Also, identic(?) code for Json isn't contains @safe modifiers:
https://github.com/rejectedsoftware/vibe.d/blob/7f5175a21bceac49e4c52f62368c7ccecd895be6/data/vibe/data/json.d#L393

**Comment by s-ludwig** [comment]
This is really an issue. I found no way to have an `opApply` that works with type inference, as well as `@safe` inference - leaving off `@safe` requires littering `@safe` code with `@trusted` when using `Bson`, and adding it requires the same for `@system` code inside loop bodies.

**Comment by denizzzka** [comment]
Probably, Dlang hasn't contains way to specify safe foreach delegate?
(I am tried to add ``@safe:`` for entry module with foreach statement, but this compilation error isn't gone.)

**Comment by denizzzka** [comment]
> Probably, Dlang hasn't contains way to specify safe foreach delegate?

same case: http://forum.dlang.org/post/n8ggs2$1d67$1@digitalmars.com

**Comment by denizzzka** [comment]
Bugzilla already contains bug description: https://issues.dlang.org/show_bug.cgi?id=15624

We need some workaround. Maybe, will help to create range struct for working with Bson?

**Comment by s-ludwig** [comment]
I've now reverted `opApply` to take a `@system` delegate (at to be `@system` itself) - the breakage was too severe. Since I couldn't find a solution that would make type *and* attribute inference work, especially if multiple possibilities loop variables are involved, I've resorted to defining `byValue`, `byKeyValue` and `byIndexValue` ranges that are `@safe`.

**Comment by denizzzka** [comment]
Maybe remove opApply at all? Since it ``@system`` and have ranges analog.

**Comment by s-ludwig** [comment]
That should probably be done indeed, but later on, with a full deprecation phase.

**Comment by denizzzka** [comment]
I think, Range completely substitutes opApply and users will not notice anything. It is wrong?

**Comment by s-ludwig** [comment]
They'll have to change from `foreach (string k, v; bson)` to `foreach (k, v,; bson.byKeyValue)`. Unfortunately it is not possible to have multiple range types in one composite and still have foreach inference work.
