### ISSUE TITLE
Parsing multi-part messages

### ISSUE THREAD

**Issue by Cosby5** [rejectedsoftware/vibe.d#1695]
In the server options it mentions the .nextPart( ) function, but I am unable to find this.

I have a dilemma, the message that comes in from my feed is multi-part and I need to process it as it comes in or the server may be sitting on the data for upwards of an hour ( and needlessly filling the memory ). The unfortunate part about this, it there's no way to have it sent in as a websocket. 

Actually what i'm doing when it comes in.

**Comment by s-ludwig** [comment]
The usual "multipart/form-data" is parsed automatically by storing file parts as temporary files on disk. The file part are stored in `req.files`, the normal fields will go into `req.form`. There is a [minimal example](https://github.com/rejectedsoftware/vibe.d/blob/master/examples/uploader/source/app.d) and a more recent [set of blog entries](https://aberba.github.io/#blog) covering the file aspect.

Anything more customized, or other multipart formats (e.g. "alternative" or "digest") would currently require manual parsing. But can also be added on top.

I've fixed the documentation, `nextPart` was a left-over from a very early version of the code (I think never publicly released).
