### ISSUE TITLE
Support for cookie expiry date

### ISSUE THREAD

**Issue by aberba** [rejectedsoftware/vibe.d#1701]
`HTTPServerResponse.setCookie` doesn't see to have a way to set expiry date for cookies. Am i missing something? This is necessary for persistent cookies.

**Comment by s-ludwig** [comment]
`setCookie` returns a `Cookie` object, that has `maxAge` and `expires` properties. If those get set before the response gets written, the corresponding cookie field should be set accordingly.

**Comment by aberba** [comment]
so like:

```d
auto c = res.setCookie(...);
c.maxAge = 10000;
c.expires = ??
```
?

**Comment by aberba** [comment]
Is there a reason `setCookie()` doesn't handle this functionality?

**Comment by s-ludwig** [comment]
Should be `c.expires = toRFC822DateTimeString(Clock.currTime(UTC()) + 10000.seconds);`.

The API is currently definitely not ideal, especially the fact that `.expires` accepts a raw string. I'm not sure if letting `setCookie` handle everything is a good idea, but something like a `Cookie.expire(Duration)` method that sets both parameters properly should be added as a minimum.

**Comment by aberba** [comment]
Yeah. That will look more cleaner

**Comment by aberba** [comment]
How is `maxAge` different from `expires`? Seems the cooking HTTP header only accepts `expires` value.

**Comment by s-ludwig** [comment]
The attributes do the same, "Expires" is the earlier one based on absolute dates and is supported also by older versions of IE, while "Max-Age" was introduced later and is simpler to use for typical applications. I don't have the exact list of supported browser versions in my head, but for IE it still makes sense to set the expires header.

**Comment by aberba** [comment]
About implementing expire in a different function, have you see how php's `set_cookie (name, value, path,  msExpire, httpOnly, ...)`. Expire value is quite important and needed to make cookies useful iñ the first place. Else session can do same as cookies do currently. `Encoding` can come after `expire` in an overload of `setCookie()`

**Comment by aberba** [comment]
I mean expire parameter in `setCookie` overload. Good idea?
