### ISSUE TITLE
HTTPClient pool how to handle connection reset by peer ?

### ISSUE THREAD

**Issue by lotusdeng** [rejectedsoftware/vibe.d#1714]
when a client use requestHTTP communicate with a http server, kill http server,
the requestHTTP catch “connection reset by peer” , how could the vibe http client
 internal close the broken socket and create new socket?

**Comment by s-ludwig** [comment]
The HTTP client checks if the connection is [still connected](https://github.com/rejectedsoftware/vibe.d/blob/0ce2515954b5e62962ae3d22fd52b4ecf64cea10/http/vibe/http/client.d#L545) and re-connects if necessary. So if everything goes right, the next request should get through as soon as the server is online again.

This is the basic idea for the `ConnectionPool` - as far as the connection pool is concerned, a connection that is created once is handled as if it would be connected eternally. Any re-connects must be handled transparently by the connection object.
