### ISSUE TITLE
TCP concurrent read/write not properly terminated if peer closes connection

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/vibe.d#1726]
Most likely the cause for #1724. This happens for the libevent and libasync drivers, not for vibe-core.

**Comment by tchaloupka** [comment]
Might be related also to #1229

**Comment by s-ludwig** [comment]
@tchaloupka I think #1229 is something else. It seems to be something specific to the OpenSSL stream implementation. I'll have to try and reproduce it on a Windows machine to be able to say more.
