### ISSUE TITLE
URL.toString messed up for tcp

### ISSUE THREAD

**Issue by John-Colvin** [rejectedsoftware/vibe.d#1732]
```D
auto url = URL("tcp://0.0.0.0:1234");
url.port = 4321;
assert(url.toString == "tcp://0.0.0.0:4321", url.toString);
```
prints `tcp::4321//0.0.0.0:1234`

**Comment by s-ludwig** [comment]
It seems like the ["//" logic](https://github.com/rejectedsoftware/vibe.d/blob/5241afafc54e1efa50baa4af28edbd3dd1774a3e/inet/vibe/inet/url.d#L68-L78) should have been reversed from the start. Almost all URL schemas have adapted the "//" style.

**Comment by s-ludwig** [comment]
PR: #1733
