### ISSUE TITLE
vibe.core.net.1726 fails intermittently when compiled with dmd-2.073.2 and the libevent configuration.

### ISSUE THREAD

**Issue by DBankov** [rejectedsoftware/vibe.d#1734]
See https://travis-ci.org/rejectedsoftware/vibe.d/jobs/217219176 for а failure example. It seems something is getting slower when compiled with dmd-2.073.2 because if I increase the sleep period from 50 to 500 msec the test succeeds consistently. I'm not sure increasing the sleep period is the correct way to fix this but I'll post a PR with it just in case there is no other fix. BTW release build as well as LDC builds (both debug and release) are working fine.

**Comment by s-ludwig** [comment]
I think it would be a good idea to restructure the test slightly, so that it returns as soon as the first task is done. A timer would be used to ensure the test doesn't hang. I'll push a fix.

**Comment by DBankov** [comment]
Wow that was fast.

And the new code looks a lot better to me.

Thanks for taking a look at this!
