### ISSUE TITLE
Json.undefined serializes to invalid Json

### ISSUE THREAD

**Issue by tchaloupka** [rejectedsoftware/vibe.d#1735]
This is related to: #1442

```D
auto json = Json();
writeln(json.serializeToPrettyJson);
```

Json should allways serialize to a valid Json I think. So probably to `null` in this case?

**Comment by dcousens** [comment]
`undefined` is [not valid JSON](http://www.json.org/),  tbh,  I'm not sure why `vibe.d` included it seeing as even `Json.undefined != Json.undefined`

**Comment by thaven** [comment]
JSON.undefined may be returned when referencing a key that is not present in a Json object. It should not be serialized to anything, except when at the root of the tree, then it should be serialized as `null`.

**Comment by dcousens** [comment]
@thaven except `Json.undefined != Json.undefined`

**Comment by thaven** [comment]
@dcousens One may argue if two non-existing 'things' should be considered equal... ;-) That is probably why the *type* of the Json object is being compared to `Json.Type.undefined`.

**Comment by dcousens** [comment]
@thaven in JS, `undefined === undefined`
