### ISSUE TITLE
Assert with TLS on 1.0.0 beta 6

### ISSUE THREAD

**Issue by Bishop92** [rejectedsoftware/vibe.d#1757]
Hi all,

When using 1.0.0.beta.6 I've this assert when using an HTTPS connection: I'm not sure...

As OpenSSLStream is a derived class of TLSStrem, the check is correct?

core.exception.AssertError@../../../../root/.dub/packages/vibe-core-1.0.0-beta.6/vibe-core/source/vibe/internal/interfaceproxy.d(111): Extraction of wrong type from InterfaceProxy.
----------------
??:? _d_assert_msg [0x16a87f6]
../../../../root/.dub/packages/vibe-core-1.0.0-beta.6/vibe-core/source/vibe/internal/interfaceproxy.d:111 nothrow @trusted vibe.internal.freelistref.__T11FreeListRefTC4vibe6stream3tls9TLSStreamVbi1Z.FreeListRef vibe.internal.interfaceproxy.InterfaceProxy!(vibe.core.stream.Stream).InterfaceProxy.extract!(vibe.internal.freelistref.__T11FreeListRefTC4vibe6stream3tls9TLSStreamVbi1Z.FreeListRef).extract() [0x15c11bb]
../../../../root/.dub/packages/vibe-d-0.8.0-beta.5/vibe-d/http/vibe/http/server.d:1845 @safe bool vibe.http.server.handleRequest(vibe.internal.interfaceproxy.InterfaceProxy!(vibe.core.stream.Stream).InterfaceProxy, vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo, ref vibe.http.server.HTTPServerSettings, ref bool, scope std.experimental.allocator.IAllocator) [0x15a62a4]
../../../../root/.dub/packages/vibe-d-0.8.0-beta.5/vibe-d/http/vibe/http/server.d:1776 @trusted void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo).__lambda4() [0x15a5c32]
../../../../root/.dub/packages/vibe-d-0.8.0-beta.5/vibe-d/http/vibe/http/server.d:1772 @safe void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo) [0x15a59de]
../../../../root/.dub/packages/vibe-d-0.8.0-beta.5/vibe-d/http/vibe/http/server.d:1647 nothrow @safe void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings, vibe.http.server.HTTPServerContext).doListen(vibe.http.server.HTTPListenInfo, vibe.http.server.HTTPServerContext, bool, bool).__lambda6(vibe.core.net.TCPConnection) [0x15a51cb]
../../../../root/.dub/packages/vibe-core-1.0.0-beta.6/vibe-core/source/vibe/core/task.d:516 _D4vibe4core4task12TaskFuncInfo76__T3setTDFNfS4vibe4core3net13TCPConnectionZvTS4vibe4core3net13TCPConnectionZ3setMFKDFNfS4vibe4core3net13TCPConnectionZvKS4vibe4core3net13TCPConnectionZ12callDelegateFKS4vibe4core4task12TaskFuncInfoZv [0x165d0a6]
../../../../root/.dub/packages/vibe-core-1.0.0-beta.6/vibe-core/source/vibe/core/task.d:541 void vibe.core.task.TaskFuncInfo.call() [0x163f135]
../../../../root/.dub/packages/vibe-core-1.0.0-beta.6/vibe-core/source/vibe/core/task.d:372 nothrow void vibe.core.task.TaskFiber.run() [0x163e6aa]
??:? void core.thread.Fiber.run() [0x1707b0f]
??:? fiber_entryPoint [0x1707872]
??:? [0xffffffff]
[main(HzkV-fin) dbg] Thread exit main (index 0) (main=true)
[main(HzkV-fin) dia] Main thread exiting

I've noticed that using the version 0.7.31 this issue is no present.

Thanks

Stefano

**Comment by s-ludwig** [comment]
The problem is that the stored type is actually a concrete `FreeListRef!OpenSSLStream`. `InterfaceProxy` doesn't support an kind of conversions, though. I've opened #1795 with a fix.
