### ISSUE TITLE
Use SCRAM-SHA-1 as default for MongoDB

### ISSUE THREAD

**Issue by wilzbach** [rejectedsoftware/vibe.d#1785]
> MongoDB no longer defaults to MONGODB-CR and instead uses SCRAM-SHA-1 as the default authentication mechanism.

https://docs.mongodb.com/manual/core/security-mongodb-cr/#authentication-mongodb-cr
Released in March 2015
https://docs.mongodb.com/manual/release-notes/3.0

Either SCRAM-SHA-1 should be the default option or the initialization should detect the MongoDB version and thus set the auth mechanism automatically if Mongo > 3

**Comment by cifvts** [comment]
To obtain this behaviour I guess [mongodb/vibe/db/mongo/connection.d](https://github.com/rejectedsoftware/vibe.d/blob/master/mongodb/vibe/db/mongo/connection.d) should be change, but this also will break existing apps that won't explicit auth mechanism. not sure if there is an wasy way to obtain version before attempt a connection.

**Comment by wilzbach** [comment]
I think most mongo instances nowadays have been upgraded, but just to be sure we can simply try the old method as a fallback on a `MongoAuthException`.

In any case, I submitted https://github.com/rejectedsoftware/vibe.d/pull/1843
