### ISSUE TITLE
Issue with dmd 2.0.75.1

### ISSUE THREAD

**Issue by andre2007** [rejectedsoftware/vibe.d#1797]
It seems there is an issue with the dmd 2.075.0-b1 and rc.2

vibe-d:utils 0.8.0-rc.2: building configuration "library"...
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\utils\hashmap.d(258,45): Error: function vibe.utils.hashmap.HashMap!(void*, uint, DefaultHashMapTraits!(void*)).HashMap.AW (IAllocator a) is not callable using argument types (shared(ISharedAllocator))
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\internal\memory_legacy.d(199,21): Error: template instance vibe.utils.hashmap.HashMap!(void*, uint, DefaultHashMapTraits!(void*)).HashMap.opIndexAssign!uint error instantiating
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\internal\memory_legacy.d(199,21): Error: function 'vibe.utils.hashmap.HashMap!(void*, uint, DefaultHashMapTraits!(void*)).HashMap.opIndexAssign!uint.opIndexAssign' is not nothrow
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\internal\memory_legacy.d(194,9): Error: nothrow function 'vibe.internal.memory_legacy.DebugAllocator.alloc' may throw
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\internal\memory_legacy.d(218,21): Error: function 'vibe.utils.hashmap.HashMap!(void*, uint, DefaultHashMapTraits!(void*)).HashMap.opIndexAssign!uint.opIndexAssign' is not nothrow
..\..\..\..\Users\D041451\AppData\Roaming\dub\packages\vibe-d-0.8.0-rc.2\vibe-d\utils\vibe\internal\memory_legacy.d(208,9): Error: nothrow function 'vibe.internal.memory_legacy.DebugAllocator.realloc' may throw
dmd failed with exit code 1.

Does not occur with 2.074.

**Comment by lionello** [comment]
`processAllocator()` changed in 5bc80e6dd653ca095a4d7d2b9bcfe33607d4d36d. Summoning @edi33416: What is the right guidance for transitioning from `IAllocator` to `shared(ISharedAllocator)`? (The last one seems to have at least one redundant "shared" for my taste?)

**Comment by andre2007** [comment]
Already solved with rc3
