### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by anton-dutov** [rejectedsoftware/vibe.d#1834]
dub.sdl

    dependency "vibe-core"   version="~>1.0.0"
    dependency "vibe-d:core" version="~>0.8.0"
    dependency "vibe-d:http" version="~>0.8.0"

    subConfiguration "vibe-d:core" "vibe-core"

    versions "VibeNoSSL"
    versions "VibeDefaultMain"

But tls is on?

    dub build --build=release
    Performing "release" build using dmd for x86_64.
    ...
    diet-ng 1.2.1: building configuration "library"...
    vibe-d:crypto 0.8.0: building configuration "library"...
    ...
    vibe-d:diet 0.8.0: building configuration "library"...
    ...
    vibe-d:tls 0.8.0: building configuration "openssl"...
    ...

1. How to exclude crypto & tls?
2. How to exclude diet compilation?

**Comment by s-ludwig** [comment]
The way to select the TLS provider has changed (#1823) and now works using configurations:
```
dependency "vibe-d:tls" version="~>0.8.0"
subConfiguration "vibe-d:tls" "notls"
```

Crypto can't be excluded, because it's needed for WebSockets and sessions.

Diet is also a fixed dependency, but I just realize now that I should have removed it for 0.8.0, as there is no reason to use it over diet-ng anymore.

**Comment by anton-dutov** [comment]
> The way to select the TLS provider has changed

Thank you, it works, but [docs](http://vibed.org/docs#advanced) outdated

> Diet is also a fixed dependency, but I just realize now that I should have removed it for 0.8.0, as there is no reason to use it over diet-ng anymore.

May be something version VibeOldDiet, but exclude by default?

**Comment by anton-dutov** [comment]
Wow, so fast =)

**Comment by s-ludwig** [comment]
> Thank you, it works, but docs outdated

Thought the same and am currently working on it :)

> May be something version VibeOldDiet, but exclude by default?

By default the dependency isn't used, so this is basically already the case. I've opened a PR to completely remove it. Using `VibeOldDiet` will then simply output a warning that it has no effect anymore.
