### ISSUE TITLE
Projects fail to build without Diet-NG

### ISSUE THREAD

**Issue by ximion** [rejectedsoftware/vibe.d#1898]
Hi!
If I compile a Vibe project without Diet-NG, I get errors like:
```
/usr/include/d/vibe/vibe/http/server.d(279): Error: undefined identifier 'DefaultFilters'
```
This, looking at the code, makes sense. So I guess you might want to make Diet a hard-dependency, fail with a better error message, or maybe fix this problem somehow, so builds without Diet still work.
Thanks!

**Comment by s-ludwig** [comment]
Hi! Diet-NG has indeed become a hard dependency as of 0.8.1, as the old implementation has been removed completely: https://github.com/rejectedsoftware/vibe.d/blob/c28ce62e33a6d4d9dea827d9f3d13c759ae79fe0/http/dub.sdl#L7
I missed how this is now handled in the meson build when looking through the PR. But tagged diet-ng 1.4.1 has been tagged with the meson.build included, so it could be added to vibe.d.

**Comment by ximion** [comment]
@s-ludwig I added a patch which resolves that in Meson (requires a minor change in Diet as well, for convenience).
I guess it might make sense then in Vibe.d to remove the version block around the Diet-NG code? (so any attempt to compile without Diet will fail for real).
