### ISSUE TITLE
renderCompat!() should allow values that implicitly convert to the specified parameter type

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/vibe.d#219]
Currently this fails with a runtime assertion:

```
void fun(HttpServerResponse res, in int test)
{
    res.renderCompat!("sometempl.dt", int, "test")(test);
}
```

A possible fix would be to change the signature of `renderCompat` from
`void compileDietFileCompat(string template_file, TYPES_AND_NAMES...)(OutputStream stream__, ...)`
to (conceptually)
`void compileDietFileCompat(string template_file, TYPES_AND_NAMES...)(OutputStream stream__, Types!TYPES_AND_NAMES args)`

See http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/post/1520

**Comment by Stretto** [comment]
with vibedist, I get Error: no property 'renderCompat' for type 'vibe.http.server.HTTPServerResponse'
