### ISSUE TITLE
registerFormInterface example docs invalid

### ISSUE THREAD

**Issue by rjmcguire** [rejectedsoftware/vibe.d#231]
registerFormInterface does not work. you have to add the url prefix as a third argument in the example.
Once you've done that it compiles but POST still doesn't work. At least not in my case.

My example:
	registerRestInterface(routes, new MyApiImpl, "/api/");

class Login {
	void index(HTTPServerResponse res) {
		res.render!("login.dt");
	}
	void postSubmit(HTTPServerRequest req, HTTPServerResponse res, string username, string password) {
		logInfo("Authenticating");
		if (username != "asdf" || password != "1234")
			throw new HTTPStatusException(HTTPStatus.Unauthorized);

		auto session = req.session;
		if (!session) session = res.startSession();
		session["User"] = "bam";
		res.redirect(req.query["next"]);
	}
}

**Comment by s-ludwig** [comment]
`registerFormInterface` has been removed and replaced by `registerWebInterface` by now.
