### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by zzzteph** [rejectedsoftware/vibe.d#38]
Hi everyone!
I just tested vibe.d vs nodejs and got pity results...
I wrote (Ctrl+C) two simples apps:
(Vibe.d)
void handleRequest(HttpServerRequest req, HttpServerResponse res)
{   res.writeBody(cast(ubyte[])"Hello, World!", "text/plain");}
static this()
{   setLogLevel(LogLevel.Trace);
    auto settings = new HttpServerSettings;
    settings.port = 8080;
    listenHttp(settings, &handleRequest);}
And nodejs
var sys = require('sys'),
http = require('http');
http.createServer(function(req, res) {
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.write('<p>Hello World</p>');
  res.end();
}).listen(8080);
Test with
ab -r -n 100000 -c 1000 http://127.0.0.1:8080/
And got results(vibe.d):
Concurrency Level:      1000
Time taken for tests:   515.134 seconds
Complete requests:      100000
Failed requests:        7662
   (Connect: 0, Receive: 2554, Length: 2554, Exceptions: 2554)
Write errors:           0
Total transferred:      13155885 bytes
HTML transferred:       1266863 bytes
Requests per second:    194.12 [#/sec](mean)
Time per request:       5151.341 [ms](mean)
Time per request:       5.151 [ms](mean, across all concurrent requests)
Transfer rate:          24.94 [Kbytes/sec] received

Results(nodejs):
Concurrency Level:      1000
Time taken for tests:   16.212 seconds
Complete requests:      100000
Failed requests:        0
Write errors:           0
Total transferred:      8100000 bytes
HTML transferred:       1800000 bytes
Requests per second:    6168.42 [#/sec](mean)
Time per request:       162.116 [ms](mean)
Time per request:       0.162 [ms](mean, across all concurrent requests)
Transfer rate:          487.93 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0   97 640.7      0    9028
Processing:     0   23  50.2     20    9831
Waiting:        0   22  50.2     20    9831
Total:          1  120 648.4     21    9831

I understand that vibe is very young project , but my I did something wrong?

**Comment by ohenepee** [comment]
Looking at the **performance figures** here (https://github.com/nanoant/WebFrameworkBenchmark)... I'm beginning to wonder if u you guys made up the figures in your benchmarks

@s-ludwig  @zzzteph  @btko02

**Comment by etcimon** [comment]
Looks like it's running on distribute and avoiding manual memory management. I wonder what the figures would be without that contention

**Comment by ohenepee** [comment]
Could someone please make the necessary pulls for the project? They seem to be more serious and consistent and updated compared to Techempower Framework Benchmarks.... I'm just a beginner, so there's little I can contribute to that project

**Comment by etcimon** [comment]
I'm not sure what you mean. Sorry if I'm being superficial, but this project with 13 stars is more serious than Techempower with 2,000 stars?

**Comment by ohenepee** [comment]
Yes that's exactly what I mean... I don't know if you've been following TFB, and if you've been... I fon't know how long, but there's a **significant lot** of inconsistencies with TFB, to list a few;

- Overdue deadlines (in the scale of months)
- Old versions (which are inherently slow, buggy, and outmoded)
- Bloated
