### ISSUE TITLE
Prevent memory leaks in vibe.http.session.MemorySessionStore

### ISSUE THREAD

**Issue by ilya-stromberg** [rejectedsoftware/vibe.d#383]
Current MemorySessionStore implementation releases memory only via `destroy(string id)` function call. It is called via `vibe.http.server.HTTPServerResponse.terminateSession()` function if user goes to a logout page.
Memory leak can happens if user destroys information about current session without visit the logout page. We use cookies without expiration time and browser will delete it in the end of session (when user close the browser). So, next time the user login again and we have got the memory leak. It can be critical for high load.
Possible solution is use timers that automatically terminate the session after specified time (for example, 24 hours by default).

**Comment by s-ludwig** [comment]
Delegating topic to #1006.
