### ISSUE TITLE
How about splitting vibe.d in sub-packages?

### ISSUE THREAD

**Issue by p0nce** [rejectedsoftware/vibe.d#395]
Since logging and allocators will make forever to enter the standard library, why not split vibe.d in subpackages? It makes more sense to depends on a small part of vibe instead of a big one.

**Comment by Korobochka** [comment]
Currently at code.dlang.org more and more packages appear with names "vibe.something extraction". This looks like a bad approach since keeping code in sync is hard. However this clearly shows a demand in separate packages.
Maybe it is time to look at this issue again.

**Comment by p0nce** [comment]
I see no real downsides to sub-packages. It often allows to drop whole dependencies.

**Comment by s-ludwig** [comment]
https://github.com/rejectedsoftware/vibe.d/tree/subpackages

**Comment by s-ludwig** [comment]
This will still have to wait a little bit, because DUB 0.9.23 has fixed an issue that prevents the split package to work correctly.

**Comment by etcimon** [comment]
> DUB 0.9.23 has fixed an issue that prevents the split package to work correctly.

I think the main solution would be to allow combining configurations/subconfiguraitons (--config=one,two,three), is this what you refer to?

**Comment by s-ludwig** [comment]
No, that's a separate issue (that would need a new concept, maybe "features", instead of configurations, because combining configurations doesn't make sense in the general case). I think the main issue was D-Programming-Language/dub#448.

**Comment by s-ludwig** [comment]
Implemented by #1329.
