### ISSUE TITLE
Add function to finalize HTTPServerResponse stream manually

### ISSUE THREAD

**Issue by ilya-stromberg** [rejectedsoftware/vibe.d#424]
This function should finalize `HTTPServerResponse.bodyWriter` and free all HTTPServerResponse resources like (keep-alive) connection. It can help to avoid unnecessary client waiting if we need to run some tasks after response to the client (like save information into DB, save information into file, send an e-mail, save information to the log and etc.).
It allows to process the same number of connections as without this feature, but client will receive response faster.
Note that FastCGI supports this option and php-fpm implements it.
See also: http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/8086/

**Comment by s-ludwig** [comment]
`HTTPServerRespose.finalize()` was added in 77284b9515345c4f008dfe6e227128c4476a2755. See also #1347.
