### ISSUE TITLE
Add ability to receive Json value as string without any casts

### ISSUE THREAD

**Issue by ilya-stromberg** [rejectedsoftware/vibe.d#491]
It can be useful for integration with third-party software.
See also: http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/10098/

**Comment by s-ludwig** [comment]
Closing in favor of #431, which touches this topic. Will probably not implemented here, but will instead probably be available for [stdx.data.json](https://github.com/s-ludwig/std_data_json).
