### ISSUE TITLE
Support a receive timeout for UDP connections

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/vibe.d#540]
Add either an overload of `receive` that takes a timeout parameter, or add a separate `waitForData` method analogous to the one in `TCPConnection`.

**Comment by Downchuck** [comment]
Was this tested in Windows? My thread is handing on a simple timeout on Win 8.1, vibe 0.7.22:
		Duration packetTimeout = dur!"msecs"(100);
		auto pack = udp_listener.recv(packetTimeout);
