### ISSUE TITLE
dub test runs out of memory

### ISSUE THREAD

**Issue by etcimon** [rejectedsoftware/vibe.d#542]
I tested this on the examples through dub run --build=unittest as well, DMD supposedly runs out of memory after doing nothing for a while. However, I only see ~1.2gb of memory usage and on my computer I still have 50% free..

![2014-02-21 10_07_26-mingw32__e_dev_spee d_externals_vibe d_examples_diet](https://f.cloud.github.com/assets/4785754/2230952/fdc44cc6-9b09-11e3-91ed-13a3a30c9fde.png)

**Comment by rayark-alvin** [comment]
Maybe it's too late. I've just found that --combined flag works
```
dub test --combined
```
