### ISSUE TITLE
Implement Linked Lists within HashMap

### ISSUE THREAD

**Issue by etcimon** [rejectedsoftware/vibe.d#557]
I'm looking for a small optimization on existence checks in the vibe.utils.hashmap HashMap. The way it is now, it loops through every possible TableEntry if the hash code was used by another key because the slot doesn't allow mutiple values. I could suggest using a linked list in replacement if another key hashes to the same value, and so the solution would be to implement TableEntry as a Variant that could be either a DList!TableEntry or a TableEntry.

This is inspired by Java's implementation of the HashMap, explained here: http://mkbansal.wordpress.com/2010/06/24/hashmap-how-it-works/

Would this seem like a good addition if I made the modification and offered a pull request?

**Comment by s-ludwig** [comment]
This would be bad for cache locality and memory use and generally results in worse performance. The only that that is important is to have the table large enough to leave enough room for collision entries, without having to iterate too much.
