### ISSUE TITLE
IPv6 unittest failure

### ISSUE THREAD

**Issue by Cauterite** [rejectedsoftware/vibe.d#562]
System: Vibe 0.7.20 -version=VibeWin32Driver, DMD 2.065.0, Windows XP 32-bit
***
In vibe.core.net there is a unittest that runs vibe.core.win32.resolveHost() with an IPv6 address (line 215):
```D
test("102:304:506:708:90a:b0c:d0e:f10");
```
which fails with "Invalid IP address string", and is the only test that fails on my system.

Investigation reveals that resolveHost() first calls WSAStringToAddress() with AF_INET, which is the IPv4 flag, and fails because the address is IPv6. Then it tries again with AF_INET6, which also fails, presumably due to this behaviour specified on the WSAStringToAddress() reference page:

> Support for IPv6 addresses using the WSAStringToAddress function was added on Windows XP with Service Pack 1 (SP1) and later. IPv6 must also be installed on the local computer for the WSAStringToAddress function to support IPv6 addresses.

Then, since resolveHost() was called with `use_dns = false`, it hits `enforce(use_dns, …)` and fails. Without this line it tries GetAddrInfoEx() which fails as well with:
>Failed to look up host 102:304:506:708:90a:b0c:d0e:f10: The requested name is valid and was found in the database, but it does not have the correct associated data being resolved for.

I'm not really sure what the best solution would be. If IPv6 support is supposed to be a dependency then perhaps a more explicit test for IPv6 support should be run when the event-driver starts. Otherwise something like `version (IPv6) {…}` might be sufficient. Or, to at least get the unittest working, perhaps a workaround function that emulates the proper behaviour of WSAStringToAddress() in the absence of IPv6 support, since all it does is parse the address string and fill a sockaddr structure.

**Comment by s-ludwig** [comment]
Won't fix because XP is EOL now.
