### ISSUE TITLE
I get empty body from a response with "Connection:close" header

### ISSUE THREAD

**Issue by mesterum** [rejectedsoftware/vibe.d#604]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4 says " the transfer-length of that body is determined by [...] 5.By the server closing the connection."

In module vibe.http.client, property InputStream *bodyReader()* of HTTPClientResponse class limits to 0 the InputStream if I don't get from the server, a response with a "Content-Length" or at least a "Transfer-Encoding" header, though I get a "Connection:close" header.
Module vibe.http.proxy behave accordingly.

**Comment by sinkuu** [comment]
I'm trying to communicate with the server that responds like this, and got empty body too.
```
HTTP/1.0 200 OK
Content-Type: text/plain

hello
```

my workaound:
```diff
diff --git a/source/vibe/http/client.d b/source/vibe/http/client.d
index 5bd334a..47c64c1 100644
--- a/source/vibe/http/client.d
+++ b/source/vibe/http/client.d
@@ -846,8 +846,12 @@ final class HTTPClientResponse : HTTPResponse {
 			m_limitedInputStream = FreeListRef!LimitedInputStream(m_client.m_stream, to!ulong(*pcl));
 			m_bodyReader = m_limitedInputStream;
 		} else {
-			m_limitedInputStream = FreeListRef!LimitedInputStream(m_client.m_stream, 0);
-			m_bodyReader = m_limitedInputStream;
+			if (m_client.m_stream.empty){
+				m_limitedInputStream = FreeListRef!LimitedInputStream(m_client.m_stream, 0);
+				m_bodyReader = m_limitedInputStream;
+			} else {
+				m_bodyReader = m_client.m_stream;
+			}
 		}
 
 		if( auto pce = "Content-Encoding" in this.headers ){
```
