### ISSUE TITLE
Bson.opDispatch sucks

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#634]
It's about the third time that I run into a bug because of opDispatch.
For example in vibe.d-0.7.18 Bson didn't yet have a toString method, writeln(Bson(1)) would correctly detect this only to test IsInputRange!Bson trying to use a non-existent range triplet (empty, front, popFront). Next I ran into `bson.array` only to follow up with `bson.remove("keyname")`. Ironically the latter adds `{"remove": "keyname"}` to the object.
I remember similar pain from `Json.opDispatch` so I'm wondering whether the syntax sugar is worth the trouble.

**Comment by ariovistus** [comment]
I just noticed is isInputRange!Bson is true, which makes Bson, Json very obnoxious if not unusable with pyd

**Comment by MartinNowak** [comment]
How about a `VibeDisableBsonOpDispatch` version identifier?

**Comment by Abscissa** [comment]
Although I realize this doesn't help at this point, opDispatch and (static) duck typing (a la ranges) just don't mix :(   &lt;fantasizing...&gt;If ranges had to declare their intent to be ranges with a trivial one line (if even that), then this wouldn't have to be a problem.

**Comment by s-ludwig** [comment]
Deprecating is an option, but a version identifier seems sub optimal, because using it would possibly break any other package in the same dependency graph that uses `Bson`. I'll start with mentioning that it's scheduled for deprecation (same for `Json.opDispatch`).

**Comment by s-ludwig** [comment]
Deprecation has been effective as of eb19676b58d26fae2ece3b0b8b4dbcc83ab73c49
