### ISSUE TITLE
WebInterface Redirect tries redirecting with port.

### ISSUE THREAD

**Issue by dariusc93** [rejectedsoftware/vibe.d#656]
Hi, I found a small possible bug with the web interface (vibe.web.web). When you attempt to redirect to another link (or domain), it will try to include the port number even when behind a proxy.) Eg if you have it redirect to /new by doing redirect("/new") it will redirect perfectly fine locally (to http://localhost:8080/new) but when behind a proxy like nginx, it will attempt to add :8080 to the domain making it attempt to redirect to http://example.com:8080/new.but fail to connect.

This does not occur with HTTPServerResponse though.

**Comment by rix0rrr** [comment]
I'm also running into this.

Also, relative paths do seem to be valid as redirect URIs, so vibe's behaviour can change:

http://greenbytes.de/tech/webdav/draft-ietf-httpbis-p2-semantics-17.html#rfc.section.9.5
