### ISSUE TITLE
Segfault when accessing session

### ISSUE THREAD

**Issue by dariusc93** [rejectedsoftware/vibe.d#674]
Hi,

I am currently having an issue with using the webinterface and sessions. When I attempt to access a page dealing with it, i get a segfault and after further debugging everything with gdb, it pointed too 

class AuthenicateService
{
	private SessionVar!(AuthSess, "AuthSess") authSess;
	@path("/login") @method(HTTPMethod.GET)
	void GetLogin(){
		auto auth = authSess;
		if(auth.isValid) //segfault
			redirect("/dashboard");
		render!("login.index.jade", auth);
	}
}

What could be the problem? 

(also the only reason why I have the files as .jade was so my IDE can detect it properly but thats not the issue)

**Comment by Geod24** [comment]
Did you find a solution ?

**Comment by dariusc93** [comment]
I dont have the issue anymore, which means it couldve been resolved in 0.7.21. I forgot all about this issue which is why I've closed it.
