### ISSUE TITLE
No upper bounds on memory use with post data

### ISSUE THREAD

**Issue by etcimon** [rejectedsoftware/vibe.d#707]
I was a little curious about the lack of upper bounds on `parseJson` while it parses by default on every HTTP request, so I made a few tests with jquery for a regular POST which looks like this:

	res.writeBody(cast(ubyte[])`<html><head><title>Hello, World!</title></head><body>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script language="javascript">
		$(document).ready(function(){
			var x = [];
			var iterations = 100000;
			for (var i = 0; i < iterations; i++) {
				x += "1265230285492504";
			}
			$.post("http://127.0.0.1:8080/", x);

		});
		</script></body></html>
	`, "text/html");

The memory use of the program grows by as much as the length of the string sent to the server (1.5MB per request for this example). Also, `VibeManualMemoryManagement` mimics the same observed behavior. I haven't gone further but it does raise a few questions about DOS vulnerabilities, the circular buffer doesn't seem to be forcing the upper bounds like I assumed.

I think this begs more thorough security tests in the future with some dedicated tools like [slowhttptest](https://code.google.com/p/slowhttptest/)

**Comment by s-ludwig** [comment]
This should at least be caught by `HTTPServerSettings.maxRequestSize`, have you tried going up to more than 2 MiB? But in general, some more anti (D)DoS measures should be an important goal. There should be no reason why a vibe.d app should have to be placed behind an anti-DoS proxy in the common case.

**Comment by etcimon** [comment]
I solved this when I developed [spd](https://github.com/etcimon/spd), although the integrated parser has to be removed. It seems to have been caused by the GC, so I'm using alternatives everywhere I can to keep memory usage low.
