### ISSUE TITLE
Support "PrivateAccessProxy" for "registerRestInterface"

### ISSUE THREAD

**Issue by s-ludwig** [rejectedsoftware/vibe.d#708]
`PrivateAccessProxy` enables the use of possibly private member functions for `@before`/`@after`. Currently, this is only supported for `registerWebInterface`.

See also http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/18639/

**Comment by schveiguy** [comment]
Just wanted to chime in and say I think `PrivateAccessProxy` is horrifically blunt and probably shouldn't be advertised, let alone expanded :)

**Comment by s-ludwig** [comment]
Interestingly, it's already supported for the REST interface due to some general refactoring of the `@before`/`@after` handling. I overlooked this ticket at the time.
