### ISSUE TITLE
MongoDB connection error when app is built without -debug flag

### ISSUE THREAD

**Issue by Lord-Evil** [rejectedsoftware/vibe.d#740]
App code is basic:

``` d
import vibe.d;
import std.stdio;

shared static this()
{
    writeln("1");
    MongoClient client = connectMongoDB("127.0.0.1");
    MongoCollection collection = client.getCollection("webengDB.user");
    collection.insert(["firstName":"Evil"]);
    writeln("2");
}
```

---

Compiling like this:

```
dmd -c -of.tmp/test.o -Isource -Iinclude -fPIC -w -version=VibeDefaultMain -version=VibeLibeventDriver -version=OPENSSL -version=Have_test -version=Have_vibe_d -version=Have_libevent -version=Have_openssl source/app.d include/vibe/appmain.d -debug

dmd -oftest ./.tmp/test.o -L--no-as-needed  -Llib/libvibe-d.so -L-ldl -L-levent_pthreads -L-levent -L-lssl -L-lcrypto -defaultlib=libphobos2.so
```

---

This would work fine and insert proper entries to the MongoDB.
But, if I remove "-debug" compiler flag and try to connect then I'll get 

```
core.exception.AssertError@source/vibe/core/connectionpool.d(96): LockedConnection value corrupted.
```

---

Vibe.d is latest git master branch (aad37da)
dmd 2.065.0-3
OS: Arch Linux 3.15.4-1 x86_64

**Comment by timotheecour** [comment]
Just ran into this issue.

I want to use libvibe-d_mongodb.a (built via dub [as a dependency of another app that depends on vibe]) into an application not built via dub (for many valid reasons which I can go into). 

as above, it works when I add -debug to my compiler command, but IMO the app that uses libvibe-d_mongodb.a should work without having to be built using -debug (which may not be desirable).

Is there a way we could fix this?

**Comment by ZombineDev** [comment]
Mixing debug and non-debug object files (and in general object files built with different compiler options) is not guaranteed at all by any D compiler, so I'm not sure DUB can do anything here.

You'll need to make sure that you're using the same compiler options (e.g. debug/release/etc) to be able to link different libraries together.
Building with `dub -v` shows the compiler command line.

**Comment by timotheecour** [comment]
could we at least make it fail at compile time by detecting whether debug was not used?
eg:
debug {static assert(0, "debug was used during initial compilation, use -debug");}
instead of failing at runtime with something hard to detect

**Comment by s-ludwig** [comment]
The problem is that this problem generally is not just about `-debug`. Any `-version=X` or `-debug=X` flag, any optional dependency, the configuration that was used, certain other flags, such as `-release` or `-fPIC` and all architecture related flags. And of course compiler and compiler version can all result in similar issues. Not all of them are even possible to detect within the compiled code.

**Comment by timotheecour** [comment]
related : just posted this on stackoverflow: http://stackoverflow.com/questions/41240093/how-to-annotate-a-compilation-output-object-library-file-with-compiler-annotat
