### ISSUE TITLE
Version for dub libraries

### ISSUE THREAD

**Issue by SerialVelocity** [rejectedsoftware/vibe.d#768]
Hey,

So when I compile a library which uses vibe.d, it complains with:
```
Warning: -version=VibeDefaultMain will be required in the future to use vibe.d's default main(). Please update your build scripts.
```

I shouldn't have to include a version for that in a library should I?

I used to have ```"versions": ["VibeCustomMain"]``` in the ```dub.json``` but that caused the main function to not be included for the applications which used this library.

**Comment by s-ludwig** [comment]
`VibeCustomMain` the default now since 0.7.26 and the warning is gone.
