### ISSUE TITLE
precompile diet templates

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#773]
Processing diet templates during CTFE becomes prohibitively slow for apps with many or big templates.
We should provide a small binary in vibe.d to precompile diet templates to D.

**Comment by s-ludwig** [comment]
There is a delayed pre-compilation feature in [diet-ng](https://github.com/rejectedsoftware/diet-ng#experimental-html-template-caching) and with @UplinkCoder's CTFE changes, this, in all likeliness, will finally become obsolete, so I'd suggest that this can be closed now.

**Comment by MartinNowak** [comment]
Definitely the better approach.
