### ISSUE TITLE
Post vibe.d to some benchmarking 3rd party?

### ISSUE THREAD

**Issue by DmitryOlshansky** [rejectedsoftware/vibe.d#798]
For instance these guys are real serious about benchmarking various HTTP frameworks:
http://www.techempower.com/benchmarks/#section=data-r9

Having D framework somewhere at the top would be nice marketing. And if we won't reach the level of top performers then it would provide us incentive to continuously improve.

**Comment by s-ludwig** [comment]
Has been added now. I'll still have to make another update to improve performance, but it is in a working state.
