### ISSUE TITLE
Statically compiling dependencies 

### ISSUE THREAD

**Issue by dariusc93** [rejectedsoftware/vibe.d#830]
Hi,

I would like to know if vibe.d have plans on statically compiling the two dependencies when building an app with vibe.d. Only reason im asking is because I have set up a script to auto deploy my application to new servers but i would also need to install libevent-dev and libssl-dev. It is not a problem too, but was just wondering

**Comment by cup** [comment]
https://github.com/vibe-d/vibe.d/issues/2282
