### ISSUE TITLE
[Question] Custom Serialization for External Types?

### ISSUE THREAD

**Issue by ColdenCullen** [rejectedsoftware/vibe.d#836]
Is there currently any way to serialize a type you don't own? For example, [Dash](https://github.com/Circular-Studios/Dash) uses [gl3n](https://github.com/Dav1dde/gl3n), and we need to be able to represent things like vectors and quaternions in serialized data. Is there currently any way to do this short of submitting a PR with custom `[to|from]Representation` methods?

**Comment by s-ludwig** [comment]
[`serializeWithPolicy`](http://vibed.org/api/vibe.data.serialization/serializeWithPolicy) was added in 0.7.23 as another way to customize foreign types, without requiring the parent container type to have custom serialization.
