### ISSUE TITLE
Documentation issue on new getDatabases function

### ISSUE THREAD

**Issue by grogancolin** [rejectedsoftware/vibe.d#899]
In the new docs, the prototype section of getDatabases function has bad looking documentation:

![image](https://cloud.githubusercontent.com/assets/4712786/5123748/afce4756-70a6-11e4-9841-f8166ba52b9f.png)

I believe this can be fixed by making the return value of this function an array, rather than the current MapResult.

auto getDatabases()
	{
		return lockConnection.listDatabases()
			.map!(info => MongoDatabase(this, info.name));
	}

-> 

auto getDatabases()
	{
                import std.array : array;
		return lockConnection.listDatabases()
			.map!(info => MongoDatabase(this, info.name)).array;
	}

**Comment by s-ludwig** [comment]
Got fixed by a DDOX update: <http://vibed.org/api/vibe.db.mongo.client/MongoClient.getDatabases>

I also fixed the ambiguous documentation text.
