### ISSUE TITLE
Can't use VS 2013?

### ISSUE THREAD

**Issue by zoujiaqing** [rejectedsoftware/vibe.d#903]
------ Build started: Project: DSite, Configuration: Debug DMD x64 ------
Building Debug DMD x64\DSite.exe...
Warning: -version=VibeDefaultMain will be required in the future to use vibe.d's default main(). Please update your build scripts.
LINK : fatal error LNK1561: entry point must be defined
Building Debug DMD x64\DSite.exe failed!
Details saved as "file://D:\Projects\DSite\Debug DMD x64\DSite.buildlog.html"
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by s-ludwig** [comment]
Sorry, I missed this at the time. For completeness: As the warning suggests, the VisualD project needs have a "-version" constant named "VibeDefaultMain"  get added ("Configuration Properties" -> "Compiler" -> "General" -> "Version Identifiers").
