### ISSUE TITLE
Diet template block default implementation.

### ISSUE THREAD

**Issue by vuaru** [rejectedsoftware/vibe.d#905]
Currently, diet template blocks cannot have a default implementation while in jade they can.

Ie.
layout.dt:
```
html

body
 block hello
  p world <-- error
```
page.dt:
```
extends layout

block hello
  p not world
```

Gives:
```
Child elements for 'include' are not supported.
```

(Which btw is also a slightly odd error, since it's *extends*, not *include*.)

**Comment by s-ludwig** [comment]
Implemented by c5d8991b19175ff655bbf82ebff8d1f873502672. The "prepend" mode is also supported:
```
extends layout

prepend hello
  p hello
```
->
```
<body>
  <p>hello</p>
  <p>world</p>
</body>
```
