### ISSUE TITLE
registerWebInterface redirects to URL with parameter names

### ISSUE THREAD

**Issue by Panke** [rejectedsoftware/vibe.d#912]
If you have a function foobar in your web interface:

```d
@path(/foo/:foo/bar/:bar)
void foobar(int _foo, int _bar) { ... }
```
and register it to a URLRouter with the default web interface settings it will redirect a request
GET /foo/1/bar/2/ 
(note the slash) to 

GET  /foo/:foo/bar/:bar

which will fail, because parsing the parameter fails.

**Comment by s-ludwig** [comment]
Fixed in 0.7.21 by 0596fbd5e5c199c4129c3e43bc80aab7814b2c1a
