### ISSUE TITLE
Missing aliases of AF_INET and AF_INET6?

### ISSUE THREAD

**Issue by Flamaros** [rejectedsoftware/vibe.d#925]
On struct NetworkAddress the family property is exposed as an ushort. I think it would be better if it was at least an alias or an enum, because for the moment the user need import himself  std.c.windows.winsock to access it.

**Comment by s-ludwig** [comment]
The goal is to gradually convert the code to use the data types from `std.socket`. I started here by accepting `AddressFamily` instead of just `ushort`, which is also publicly imported.
