### ISSUE TITLE
INet URL fails to parse ipv6 addresses

### ISSUE THREAD

**Issue by mingodad** [rejectedsoftware/vibe.d#940]
I was trying to use httpclient with an ipv6 address and discovered that the URL parser do not works with ipv6 (http://[::ffff:7f00:1]:8080/)  (even chromium do not work with it but firefox works).

When URL try to parse "http://[::ffff:7f00:1]:8080/" it expects the first ":" after the"//" to be the port separator but with ipv6 it's not.

**Comment by s-ludwig** [comment]
Fixed by #1341.
