### ISSUE TITLE
How to build with libev?

### ISSUE THREAD

**Issue by Paxa** [rejectedsoftware/vibe.d#953]
When I run `dub --config=libev` it says:

```
Error executing command run: Unknown build configuration: libev
```

How should I make it?

**Comment by s-ludwig** [comment]
When building a dependent project, you currently have to select the vibe.d configuration using `"subConfigurations": {"vibe-d": "libev"}` in the project's dub.json. The `--config` switch only applies to configurations of the root project itself. However, the libev back end is experimental and only includes the minimum functionality to run a TCP based server. If no one volunteers to complete it, it's also quite likely that it will be removed at some point in favor of the new libasync back end.

**Comment by Paxa** [comment]
Thanks it worked
