### ISSUE TITLE
libasync driver: cycle detected between modules with ctors/dtors

### ISSUE THREAD

**Issue by japplegame** [rejectedsoftware/vibe.d#956]
dmd 2.066.1, Linux x86_64
> object.Exception@src/rt/minfo.d(162): Aborting: Cycle detected between modules with ctors/dtors:
> vibe.core.core -> vibe.core.driver -> vibe.core.drivers.native -> vibe.core.drivers.libasync -> vibe.core.core

**Comment by etcimon** [comment]
Are you launching any specific threads or do you have an example in mind?

**Comment by etcimon** [comment]
I think this commit might fix it:
https://github.com/etcimon/libasync/commit/dbcc88c5877609cfa81cd3cf3917ade7d023f482

Can you try again?

**Comment by japplegame** [comment]
> Are you launching any specific threads or do you have an example in mind?

I just tried to switch from libevent (works well) to libasync. My application uses only one additional thread (`core.thread.Thread`) for logging .
> Can you try again with a pull of libasync master?

It doesn't help. :(

**Comment by japplegame** [comment]
Another my project causes compilation error:
`dub/packages/vibe-d-0.7.22/source/vibe/core/drivers/libasync.d(406): Error: undefined identifier Path, did you mean function path?`

**Comment by japplegame** [comment]
I'll try to make a test-case for this.

**Comment by etcimon** [comment]
> Another my project causes compilation error:
> dub/packages/vibe-d-0.7.22/source/vibe/core/drivers/libasync.d(406): Error: undefined identifier Path, did you mean function path?

There should be an `import libasync.internals.path` at the top of drivers/libasync.d, which replaces the `vibe.inet.path` conditionally.

I'm not sure how this didn't get caught before, I'm setup for git master right now and that one doesn't build it for sure.

> I just tried to switch from libevent (works well) to libasync. My application uses only one additional thread (core.thread.Thread) for logging .

This thread might be culprit, I'd run a test with a foreign log thread. I might have to change the workaround at core.d:1317 to return on any thread that isn't a worker.

**Comment by japplegame** [comment]
Test case is very very simple :smile:
```d
/// app.d
import vibe.core.core;
```
dub.json:
```json
{
	"name": "test",
	"dependencies": {
		"vibe-d": "==0.7.22"
	},
	"subConfigurations": {
		"vibe-d": "libasync"
	},
	"versions": ["VibeDefaultMain", "VibeLibasyncDriver"]
}
```
dub.selections.json:
```json
{
	"fileVersion": 1,
	"versions": {
		"vibe-d": "0.7.22",
		"libevent": "2.0.1+2.0.16",
		"openssl": "1.1.3+1.0.1g",
		"libev": "4.0.0+4.04",
		"libasync": "0.6.5"
	}
}
```

**Comment by etcimon** [comment]
Hmm.. I downgraded my DMD, druntime, phobos to 2.066.1 and still can't get this. Can you paste the output of your `dub run`?

**Comment by etcimon** [comment]
Actually I got it now. fix is very simple, just import `vibe.appmain` before `vibe.core.core` ;)

**Comment by japplegame** [comment]
It is not a good solution. Just switched to VibeCustomMain and got it again.
dub.json
```json
"versions": ["VibeDefaultMain", "VibeLibasyncDriver"]
```
app.d
```d
import vibe.appmain;
import vibe.core.core;
void main() {}
```

**Comment by etcimon** [comment]
Could you test your projects again with this fix? =)

**Comment by japplegame** [comment]
Project successfully compiled and started. But one of task (spawned by `runTask`) freezes during fetching remote web page. I'll dig it later.

**Comment by etcimon** [comment]
> Project successfully compiled and started. But one of task (spawned by runTask) freezes during fetching remote web page. I'll dig it later.

Ok! Looks like you could use a `LogLevel.trace` report. Are you on libasync 0.6.6?

**Comment by japplegame** [comment]
>Are you on libasync 0.6.6?
No. I on 0.6.5 (default version for vibe.d 0.7.22). I'll test it, but not right now.

**Comment by etcimon** [comment]
Ok, you should definitely use the `fix-libasync` branch and v0.6.6 because of an issue with TCP connections not closing correctly. https://github.com/rejectedsoftware/vibe.d/pull/943

**Comment by nin-jin** [comment]
I have same problem: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/61634014
Sources & install scripts: https://github.com/nin-jin/FrameworkBenchmarks/tree/vibed/frameworks/D/vibed

What I have to do to get it working?

**Comment by etcimon** [comment]
Your problem seems different, in your case the cycle is:

vibe.http.server -> vibe.http.dist -> vibe.http.server

On my end it compiles fine with DMD 2.067.1, maybe you could update DMD ?

**Comment by nin-jin** [comment]
Same problem with DMD 2.067.1
Install.sh: https://github.com/nin-jin/FrameworkBenchmarks/blob/vibed/frameworks/D/vibed/install.sh
Result: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/61669319

**Comment by nin-jin** [comment]
Same problem with dmd 2.067.1: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/61734278

**Comment by nin-jin** [comment]
Can someone fix this problem?
Code is easy.
Then we can compare D and VibeD with other languages and frameworks on https://www.techempower.com/benchmarks/

**Comment by etcimon** [comment]
Does it run vibe.d 0.7.19 ? I'll do some tests but I think you should change that to 0.7.23

**Comment by etcimon** [comment]
This was shown to be due to the use of `--build-mode=singleFile`
