### ISSUE TITLE
data.json: nan should not be serialized to "undefined"

### ISSUE THREAD

**Issue by tomykaira** [rejectedsoftware/vibe.d#958]
Problem: The serialization object including `NaN` is invaild JSON.

```d
auto j = Json.emptyObject;
j["float"] = Json(double.init);
assert(j.toString == `{"float":undefined}`);  // literal "undefined" is invalid
```

According to [existing unittests](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/data/json.d#L1721), this is intended behavior, but IMO, not acceptable as implementation of JSON serializer.
Serialization must not create invalid JSON data without error notification.

I understand it is difficult to approach from compatibility point of view, but I appreciate if one of following fixes are introduced.

- Throw an exception because it is `NaN` input is not permitted [1]
- Serialize `NaN` to `null` (as ECMAScript does [2])

1. [RFC 4627 - The application/json Media Type for JavaScript Object Notation (JSON)](http://tools.ietf.org/html/rfc4627) 2.4. Numbers
2. [PDF: Final draft Standard ECMA-262 edition 5.1, March 2011 (Rev. 6)](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) p.208

**Comment by NfNitLoop** [comment]
There's a similar issue with the default `undefined` value in Json: 

~~~
Json j;
assert(j.toString == "undefined")
~~~

These kinds of values are time bombs for JSON in D.  They give neither compile-time nor runtime errors, they just result in invalid output that can't be parsed by REST clients!

**Comment by intrica** [comment]
Okay so when I did this, I also made another change to our local fork of vibe.d which I've had to reapply for every upgrade. I wasn't sure if people would like the behaviour, but here is my logic.

For a JSON object, a value that is not set should simply not appear in the structure. I don't particularly see why we should have 'null' in there, anymore than we should have undefined. If the key isn't set, it shouldn't exist. For a value, I agree that null is the better value to set to. 

We worked with this by modifying writeJsonString. A NaN is output as null, and ignored if it is part of an object.

Now some people may not like this idea as if something is missing from the structure, it needs to be optional. But if you are going to allow NaN to be serialised, then it really is an optional value anyway.

If you guys are okay with the idea of just modifying the serialised version of the string, then I'm happy to submit my branch as a pull request.

**Comment by s-ludwig** [comment]
Fixed by https://github.com/rejectedsoftware/vibe.d/pull/1548

@intrica: I'm not sure if omitting `null` in objects is a good idea in general. After all, it still carries information and most importantly, such a change could break a lot of code. Now, NaN is of course a special case, if you'd count it as `undefined` instead of as `null`, but I'd again prefer to follow the ECMA script JSON conversion rules, which state `null`, AFAIR.
