### ISSUE TITLE
stream.operation.readUntil: generates broken output when str is changed while reading

### ISSUE THREAD

**Issue by tomykaira** [rejectedsoftware/vibe.d#960]
When used with `GzipInputStream` and a specific file, content of `str` set by `peek()` [opeartion.d#L152](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/stream/operations.d#L152) is implicitly changed by [read() call in skip](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/stream/operations.d#L138).
This results in broken output from [`dst.put`](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/stream/operations.d#L193).

Simple solution is to replace `stream.peek()` with `stream.peek().dup`, which works correctly, but the performance effect may be too much.

Here are test code, but I cannot provide the problematic file, because it contains confidential data.
It is log data with 5 lines and each line contains 100-5000 ascii characters.
I tried to make a similar file, but couldn't.
So sorry about inconvenience.

```d
unittest {
    import vibe.core.file;
    import vibe.stream.zlib;
    auto fs = openFile("problematic.txt.gz");
    scope(exit) fs.close();

    string byline = "";
    auto gis = new GzipInputStream(fs);
    while (!gis.empty()) {
        byline ~= cast(string) readLine(gis, size_t.max, "\x0a") ~ "\x0a";
    }
    fs.seek(0);
    auto gis2 = new GzipInputStream(fs);
    string byall = cast(string) readAll(gis2);
    assert(byline == byall);
}
```

**Comment by s-ludwig** [comment]
Fixed by 78140aa1a05f483ae143d38ddedb326c8f791311
