### ISSUE TITLE
listenTCP with libasync causes connection.localAddress.family to be AF_UNSPEC

### ISSUE THREAD

**Issue by GeorgeSapkin** [rejectedsoftware/vibe.d#961]
In the following example `NetworkAddress.toAddressString()` fails with `called for invalid address family` (family is `AF_UNSPEC`) when switching to libasync driver. Default libevent driver works as expected and I would expect the same behavior from libasync. Reproducible on both Linux and Windows with vibe 0.7.22 and libasync 0.6.6.

```D
listenTCP(port,
    (connection)
    {
        auto addr = connection.localAddress.toAddressString;
    });
```

Not sure where this should be reported.

**Comment by Geod24** [comment]
Ping @etcimon :)

**Comment by etcimon** [comment]
My bad, thanks for catching it!

**Comment by etcimon** [comment]
This can be closed now
