### ISSUE TITLE
Diet template inline tag support.

### ISSUE THREAD

**Issue by vuaru** [rejectedsoftware/vibe.d#964]
I'm really missing this jade 1.0 feature:
```
p hello #[i world] sun
```
```
<p>hello <i>world</i> sun</p>
```

ala https://github.com/jadejs/jade/pull/1323

**Comment by s-ludwig** [comment]
This is now implemented as part of Diet-NG, which will be the successor of the current implementation at some point. Development will concentrate on that instead.
