### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by GanMatt** [rejectedsoftware/vibe.d#971]
Building: tcp-separate-example (Default)
Performing main compilation...
/usr/local/bin/dub build "tcp-separate-example" "--build=plain"
Building package tcp-separate-example in /Users/Matt/Downloads/vibe.d-master/examples/tcpseparate/<br>Building vibe-d ~master configuration "libevent", build type plain.<br>Running dmd...<br>Building tcp-separate-example ~master configuration "application", build type plain.<br>Compiling using dmd...<br>Linking...<br>ld: library not found for -levent<br>clang: error: linker command failed with exit code 1 (use -v to see invocation)<br>--- errorlevel 1<br>FAIL .dub/build/application-plain-posix.osx-x8664-dmd_2066-28E54944018C41958DFE4BCE71BFBAF6/ tcp-separate-example executable
Error executing command build: dmd failed with exit code 1.

Exit code 2
Build complete -- 1 error, 0 warnings

---------------------- Done ----------------------

Build: 1 error, 0 warnings

**Comment by Geod24** [comment]
You need some additional libraries installed.
See the readme: https://github.com/rejectedsoftware/vibe.d#additional-setup-on-mac-using-brew

**Comment by etcimon** [comment]
If you're running vibe.d from git master you can also add `"subConfigurations": { "vibe-d": "libasync" }` to the dub.json file to use a TCP driver that doesn't require any additional installations.

**Comment by etcimon** [comment]
I think a lot of newcomers could test this out more easily if the driver was selected by default =)

**Comment by Geod24** [comment]
@etcimon : I thought about it when answering, but I'm not familiar with it. Does it implements everything libevent has ?

**Comment by etcimon** [comment]
yes

**Comment by Geod24** [comment]
Is https://github.com/rejectedsoftware/vibe.d/pull/943#issuecomment-68077980 still valid ?

We could provide libasync in debug mode, and libevent in release until libasync / D catches up. Then we get the better of both world. The only problem is if there are bugs in one of the libraries.

**Comment by etcimon** [comment]
> Is #943 (comment) still valid ?

Yes, the benchmarks are a little faster with libevent for pure I/O, but I doubt this would be the bottleneck in most vibe.d applications. In my experience, it's generally more stable even in release mode.

**Comment by Geod24** [comment]
Maybe we could move that discussion to a P.R. then :)
